Add Customer onboarding template
airplanedev/templates pull request #10
Opened 2022-09-16 00:23 UTC by kellymtrinh

![Screen Shot 2022-09-15 at 5 23 30 PM](https://user-images.githubusercontent.com/8205327/190530908-1afccd2f-3b2c-4d5a-bd1f-dd890b9aec98.png)

2022-09-26 20:35 UTC, rose-huang requested changes
Looks great so far, thanks Kelly! sorry it took so long to review 😢 

views is trying out this new thing where we have 2 reviewers so can you add another reviewer among (Stephen, Zhan, and George)?

also: Views init should create a tsconfig that you should include in the customer_onboarding_dashboard toplevel directory.
also please create a README with instructions for how to use this template (see other templates for examples)

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/.gitignore
> +.airplane-view
you can remove this, we auto generate a git ignore upon cloning

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/demo_create_account.task.yaml
> +name: "[Demo] Create Account"
nit: names should not have [Demo] and should be sentence case - "Create account". Same for other tasks and views. Slug should still have demo_ prepended though!

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/demo_create_user.sql
> +VALUES(:user_id, :account_id, :email, :name, :title,  :role)
I think it would be better to not ask for a user id but suggest the next available user id, similar to how you suggest the account id when creating an account

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.yaml
> +slug: customer_onboarding_dashboard
prepend with demo_

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.yaml
> +name: Customer Onboarding Dashboard
Make this title case

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +      <Title order={2}>Create new account</Title>
I think Trijeet may edit the title sizing but maybe we should make this and the Onboard accounts title order 3 instead so it looks more noticeable different ? and update other titles to be smaller

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +    <Form
Let's wrap this in a stack and make it not take up the full width

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +      alert(`Created Account!`);
```suggestion
      alert(`Created account!`);
```

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +      alert(`Failed creating account issue with error: ${error.message}`);
```suggestion
      alert(`Failed creating account with error: ${error.message}`);
```

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +      <Table
can you add columns to this Table so that the labels are sentence case? if you look at other examples in the templates repo, we define them as a constant underneath and set `cols={accountsCols}`

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +  const { accountId } = props;
```suggestion
const UpdateRegion = ({ accountId}) => {
```

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +        />{" "}
nit: do we need {" "}? if not, remove

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +          <UpdateRegion accountId={selectedAccount?.id as string} />
For update region and the create user form, can you hide them if you've already done that step? for example, if I already set the country, can we just hide the country form?

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.tsx
> +        <Stack>
maybe try a horizontal stack so both the form and the update region are side by side so the layout looks better?

2022-09-26 20:35 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.yaml
> +slug: customer_onboarding_dashboard
also, I am encouraging people to name their view something different from the top-level directory for the template. you could try calling it `customer_onboarding` or something like that. just because `customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding_dashboard.view.yaml` seems confusing

2022-10-03 22:17 UTC, kellymtrinh commented
Thanks for all the feedback @rose-huang! Adding a second reviewer like you mentioned.
New URL (since I changed the slug on staging) is https://web.airstage.app/views/vew20221003zpg6hevf6ru?__env=prod

The main issue I'm still having is the widths for the forms doesn't apply, so they aren't each taking up 1/2 and 1/2.

2022-10-04 20:33 UTC, rose-huang requested changes
Mostly reviewed the template for consistency with other templates - would be nice if @stepzhou reviews the view code more in depth

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/create_user.sql
> +INSERT INTO
what is this using to format? I think when I pulled your code and formatted with pg formatter it was different. same for other sql files

```
INSERT INTO users ("id", "account_id", "email", "name", "title", "role")
    VALUES ((
            SELECT
                count(1)
            FROM
                users),
            :account_id,
            :email,
            :name,
            :title,
            :role)
RETURNING
    "id",
    "account_id",
    "email",
    "name",
    "title",
    "role";
```

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.yaml
> +# Used by Airplane to identify your view. Do not change.
nit - lets rename the folder with the view to customer_onboarding so it matches the name of the view/view yaml

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/create_account.task.yaml
> +- name: company name
nit:
```suggestion
- name: Company name
```

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/create_user.task.yaml
> +- name: account_id
nit: Account ID or something more readable, capitalize the other names of parameters and make them sentence case

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/create_user.task.yaml
> +- name: account_id
same for the other sql yamls

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +    label: "Company Name",
nit: sentence case "Company name". same for other column names

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +      <Stack.Item width="1/2">
nit: I think there should be different indentations - try auto formatting this?

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +        `Added updating account region! Successfully onboarded account ${accountId}.`
nit: just because we update the region doesn't actually mean the account is onboarded if there are no users so this is a bit confusing. 

also there is an error message if you try to submit the same update region form twice without changing the country, maybe you can disable the button and add a row in the table or text in the card with the region to make it more clear  -
<img width="476" alt="Screen Shot 2022-10-04 at 4 25 38 PM" src="https://user-images.githubusercontent.com/34196250/193919519-931b1c3e-94a0-453b-8853-bb14e001c811.png">

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +    <Form
maybe we should make this half width or like 1/4 width by wrapping in a stack so it looks better?

2022-10-04 20:33 UTC, rose-huang commented on customer_onboarding_dashboard/README.md
> +- If you plan on using this on a different database resource than the demo database, change the `[Demo DB]`  resource in `create_account.task.yaml`, `create_user.task.yaml`, and `list_new_accounts.ta
nit: you use "demo_db" the slug instead of the resource name in the yaml files so let's make this the same. I think the name works and is what other people have been using in their yaml files so we can go with that one unless team tasks has a guidance to use slug?

2022-10-06 18:53 UTC, kellymtrinh commented on customer_onboarding_dashboard/tasks/create_user.sql
> +INSERT INTO
I used pg formatter but I have 
```
 pg_format --version
pg_format version 5.3
```

2022-10-06 19:03 UTC, kellymtrinh commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +        `Added updating account region! Successfully onboarded account ${accountId}.`
I made the region required so you don't get the undefined error. I updated the messaging to say that the region was added and not that the account was onboarded- I don't think we can make it a true "this account is fully onboarded" without adding even more tasks 😅 or db schema more complicated

2022-10-06 19:19 UTC, kellymtrinh commented on customer_onboarding_dashboard/tasks/create_user.sql
> +INSERT INTO
Updated though with a diff version- let me know if that's better? (It looks better to my eyes 😅 )

2022-10-06 20:42 UTC, kellymtrinh commented on customer_onboarding_dashboard/customer_onboarding_dashboard/customer_onboarding.view.tsx
> +    <Form
Made it 1/2 width- hopefully looks better!

2022-10-07 15:56 UTC, rose-huang approved these changes

2022-10-07 15:56 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.tsx
> +    label: "Signup date",
nit: can you try to get this date to look a bit more readable?

maybe you could try using a date column (https://docs.airplane.dev/views/table#column-types) although not sure what it looks like if you have a time

or maybe outputtransform with some javascript helper to convert date?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

2022-10-07 15:56 UTC, rose-huang commented on customer_onboarding_dashboard/tasks/create_user.task.yaml
> +    title: "{{params.title}}"
nit: new line

2022-10-07 16:51 UTC, stepzhou approved these changes
Looks great!

2022-10-07 16:51 UTC, stepzhou commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.tsx
> +      alert(`Created account!`);
Would be nice to replace these alerts with the native Views notifications. Docs are currently in review https://github.com/airplanedev/docs/pull/441

2022-10-07 17:34 UTC, kellymtrinh commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.tsx
> +      alert(`Created account!`);
Hmmm I upgraded to the latest version and importing
`showNotification` and trying to use it crashes

2022-10-07 17:39 UTC, stepzhou commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.tsx
> +      alert(`Created account!`);
Ooof. Can you post the crash in `proj-views`? Don't block merging this on adding `showNotifications`. We can add it later

2022-10-07 18:22 UTC, rose-huang commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.yaml
> +name: Customer onboarding dashboard
oh also this is a super nit but could you rename this and the slug to "Customer onboarding" to match the file names?

2022-10-07 19:44 UTC, kellymtrinh commented on customer_onboarding_dashboard/customer_onboarding/customer_onboarding.view.tsx
> +      alert(`Created account!`);
Nvm this is resolved- possibly an old version of CLI and needing to clear our the `airplane-view` folder.

2022-10-07 20:47 UTC, merged