Add postgres admin panel
airplanedev/templates pull request #100
Opened 2023-06-06 14:54 UTC by kkoppenhaver

As part of our engineering workflows launch, we want to create an admin panel that users can use to interact with Postgres. This template allows users to run `SELECT` queries, but requires approval for any other queries.

Slack thread with discussion: https://airplanedev.slack.com/archives/C01DYGWC3P0/p1686063586092449
Task in the demo account: https://app.airplane.dev/tasks/tsk20230606zm6icqypdos?__env=prod

2023-06-06 14:59 UTC, kkoppenhaver commented on postgres_admin_panel/tasks/query_database.airplane.ts
> +      const { ok } = await airplane.prompt(
Is there anything we can do here to provide feedback to the user that their query is waiting for approval? Right now, nothing happens and it just looks like your query didn't run...

2023-06-06 15:00 UTC, kkoppenhaver commented on postgres_admin_panel/tasks/query_database.airplane.ts
> +    if (!query.includes("select")) {
Should we be doing something else here to sanitize the query and make sure we don't just give any user the ability to run arbitrary queries against the DB? Even though that's the purpose of this tool, it feels like we should lock things down a bit more.

2023-06-06 17:35 UTC, kkoppenhaver commented on postgres_admin_panel/tasks/query_database.airplane.ts
> +    if (!query.includes("select")) {
Feedback in Slack thread (https://airplanedev.slack.com/archives/C01DYGWC3P0/p1686063586092449): we will use an SQL parser package to detect SELECT queries.

2023-06-06 22:49 UTC, geodn requested changes

2023-06-06 22:49 UTC, geodn commented on postgres_admin_panel/.gitignore
> +/node_modules
This should be covered by the main gitignore: https://github.com/airplanedev/templates/blob/main/.gitignore

Can remove this file

2023-06-06 22:49 UTC, geodn commented on postgres_admin_panel/package.json
> +    "@airplane/views": "^2.1.1",
Hmm I think we typically pin these dependencies (at least the airplane ones), see https://github.com/airplanedev/templates/blob/main/stripe_billing_dashboard/package.json

2023-06-06 22:49 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +    if ("select" !== ast[0].type) {
nit: might want to make sure this works with empty ast, e.g. if user passes " "

or generally gracefully handle malformed inputs

2023-06-06 22:49 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +    const query = params.postgres_query.toLowerCase();
Is lowercasing still needed?

2023-06-06 22:49 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +    return run.output["Q1"];
Since we allow users to type in multiple statements in the box, maybe we should check if Q2 is a key and if so return `run.output`?

2023-06-07 02:03 UTC, kkoppenhaver commented on postgres_admin_panel/.gitignore
> +/node_modules
Good call. This got added by `airplane init`, but it doesn't make sense to include when we're in the templates directory context.

2023-06-07 02:36 UTC, kkoppenhaver commented on postgres_admin_panel/query_database.airplane.ts
> +    return run.output["Q1"];
Yeah thinking more about this, I think we could just return `run.output` regardless.

2023-06-07 02:46 UTC, kkoppenhaver commented on postgres_admin_panel/query_database.airplane.ts
> +    if ("select" !== ast[0].type) {
Good call. I've added a try/catch that should handle any malformed queries, as well as a statement that returns an error if an empty query is passed.

<img width="1269" alt="Screenshot 2023-06-06 at 9 43 12 PM" src="https://github.com/airplanedev/templates/assets/2965444/fb561049-9b43-48c2-a9df-30a7b01a5c56">

2023-06-07 15:30 UTC, geodn submitted a review, later dismissed

2023-06-07 15:30 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +    if (0 === params.postgres_query.trim().length) {
Hmm I think it would be cleaner to put this below astify, and instead just check that ast.length > 0. Up to you

2023-06-07 15:30 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +        `Your query was empty. Enter at least one database query run this Task again.`
"Enter at least one database query and run this task again"

2023-06-07 15:30 UTC, geodn commented on postgres_admin_panel/query_database.airplane.ts
> +    /*eslint-disable no-unused-vars*/
Can we get rid of this?

2023-06-07 17:26 UTC, leeweisberger approved these changes
lgtm after comments are addressed!

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/README.md
> +- To configure who is able to approve database queries other than `SELECT` queries, set up a [group](https://docs.airplane.dev/platform/permissions) and update `query_database.airplane.ts` with that
I would just link to these docs: https://docs.airplane.dev/tasks/approvals and not try to explain it too much here.

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +      "This task passes the query parameter to the linked Postgres resource and returns the results.",
query parameter -> SQL query

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +        description: "The database query to be run",
remove `be`

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +      db: "demo_db",
Add a comment saying to change this to the database you want to run queries on

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +const { Parser } = require("node-sql-parser");
Use imports instead of require

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +    let ast;
Type this value

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +    }
Can this happen?

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +    if ("select" !== ast[0].type) {
Can the ast be truthy but empty? If so this will throw an error

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +      await airplane.display.json(params.postgres_query);
imo this looks pretty bad as json and also we show the params in the run. I think you can remove this

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +        description: `A user is attempting to run the database query listed above. Review the query and if it looks correct, select OK to allow the query to run.`,
I think this can be a bit terser. 

`Allow <user name> to execute the query?` where <user name> is the user's name via runtime env var

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/demo_query_database.airplane.ts
> +          groups: ["engineering_workflows"],
If they don't have this group, this template will fail right? Maybe make this `admins` which is a group everyone gets by default?

2023-06-07 17:26 UTC, leeweisberger commented on postgres_admin_panel/tsconfig.json
> +    "jsx": "react-jsx"
This would indicate this support views, but it doesn't. Can you replace this file with the tsconfig that gets generated for a task?

2023-06-07 17:28 UTC, joshma reviewed
Hmm maybe I'm missing context on this, but is this originally what we intended with the postgres admin panel? As is, this isn't quite an admin panel, this is just a single task to run a query? I'd expect an admin panel to have some tables to view common things  (list of schemas, tables, users maybe), run a query against a table, see some stats, etc.

2023-06-07 20:20 UTC, geodn commented
Sorry one more thing: I think you might need to check that all individual statements are selects, otherwise there is a hole if you do something like this:

```
SELECT * from my_table;

INSERT INTO my_table VALUES ...;
```

2023-06-13 19:57 UTC, kkoppenhaver commented on postgres_admin_panel/tsconfig.json
> +    "jsx": "react-jsx"
This is being converted back to a view, so this will be relevant again.

2023-06-13 19:58 UTC, kkoppenhaver commented
Per some internal conversations, we're converting this to be more of an actual admin panel, with some additional stats about the database itself. I'll make sure all the task-specific comments are resolved, finish building out this view and then re-request a review from the folks on this PR.

2023-06-13 20:20 UTC, kkoppenhaver commented
> Sorry one more thing: I think you might need to check that all individual statements are selects, otherwise there is a hole if you do something like this:
> 
> ```
> SELECT * from my_table;
> 
> INSERT INTO my_table VALUES ...;
> ```

This is now handled in the latest round of feedback adjustments.

2023-06-13 20:21 UTC, kkoppenhaver commented on postgres_admin_panel/demo_query_database.airplane.ts
> +    if ("select" !== ast[0].type) {
This is handled by looping through each query to check if it's a SELECT query.

2023-06-13 20:22 UTC, kkoppenhaver commented on postgres_admin_panel/demo_query_database.airplane.ts
> +      "This task passes the query parameter to the linked Postgres resource and returns the results.",
Not quite sure what you mean here. Do you mean instead of taking the query as a param it should be a separate SQL task or something? The query param is already typed `sql`.

2023-06-15 20:44 UTC, kkoppenhaver commented
This is now a View with a few tasks running inside it, so I'm going to request another review even if it's already been approved. I've gone through and adjusted casing, etc to accommodate the feedback from my other recent PRs so this one should hopefully be pretty straightforward.

The one open item still is that if you run a query that requires approval, indicating in the View that approval has been requested is still tripping me up a bit. I tried doing the query parsing in the View itself, but it triggers a bug that looks very similar to [this one](https://github.com/aws/aws-sdk-js/issues/2141), so I'm assuming the views just can't import/use packages of that particular type?

Some guidance there would be appreciated, otherwise this is ready for another look.

2023-06-16 05:03 UTC, geodn reviewed
Keanan, `node-sql-parser` doesn't work in a view because it's node code, and it hasn't been written to work with browsers. In nodejs things like `global` are defined and in the browser things like `window` are defined.

I think this library should work for parsing sql from a view: https://github.com/pganalyze/pg-query-emscripten

2023-06-16 05:04 UTC, geodn commented
@kkoppenhaver left a couple comments. I'll be OOO next week so taking myself off the reviewers list for now, but if this is still in progress when I'm back, happy to look again!

2023-06-16 23:15 UTC, joshma commented on postgres_admin_panel/.gitignore
> +/node_modules
was this addressed?

2023-06-16 23:17 UTC, joshma commented on postgres_admin_panel/tasks/list_active_connections.task.yaml
> +# Full reference: https://docs.airplane.dev/tasks/task-definition
@kkoppenhaver @rose-huang I think we just need stricter and clearer coding guidelines. I think I mentioned this in the last PR, but these tasks shouldn't have all these comments here, we should clean it up, consistently format things (the .sql files aren't formatted I believe), etc.

2023-06-20 05:04 UTC, kkoppenhaver commented on postgres_admin_panel/tasks/list_active_connections.task.yaml
> +# Full reference: https://docs.airplane.dev/tasks/task-definition
Updated this to pattern-match against the `customer_insights_dashboard template.

  - Comments removed (except about replacing `demo_db` and the `# Full reference` comment, which the insights dashboard has)
  - SQL files are indeed formatted from what I can see. Spacing and line breaks similar to the insights dashboard.

2023-06-20 05:25 UTC, kkoppenhaver commented on postgres_admin_panel/demo_query_database.airplane.ts
> +      "This task passes the query parameter to the linked Postgres resource and returns the results.",
Because we're doing the query parsing, notification and approval flows, etc, I think this has to be a non-SQL task, right?

2023-06-20 19:59 UTC, rose-huang requested changes

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/postgres_admin_panel.airplane.tsx
> +import PgQuery from "pg-query-emscripten";
let's add @types/pg-query-emscripten to dev dependencies


<img width="984" alt="Screenshot 2023-06-20 at 2 59 48 PM" src="https://github.com/airplanedev/templates/assets/34196250/f2d29fbd-ef4a-45ef-81b2-ff36bb102891">

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/postgres_admin_panel.airplane.tsx
> +                label: "Client Address",
```suggestion
                label: "Client address",
```

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/postgres_admin_panel.airplane.tsx
> +      console.log(error);
should we show a notification instead of console logging the error? I'll leave this up to you

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/postgres_admin_panel.airplane.tsx
> +        {output &&
let's gracefully handle the case where output is an error (such as when I reject the prompt that lets me execute a drop statement)

RN it has an error modal because the Table component breaks  and looks like this, which looks like there is a bug in the template. We could just show the error message instead

<img width="1381" alt="image" src="https://github.com/airplanedev/templates/assets/34196250/65713bf4-71a0-4aa0-afba-2ee6ed92f9b9">

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/tasks/list_active_connections.sql
> +  4 desc;
can you run pgformatter on the SQL files?
```suggestion
SELECT
  client_addr,
  usename,
  datname,
  count(*)
FROM
  pg_stat_activity
GROUP BY
  1,
  2,
  3
ORDER BY
  4 DESC;

```

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/tasks/list_tables.sql
> +select
```suggestion
SELECT
  relname,
  pg_size_pretty(pg_total_relation_size(relname::regclass)) AS full_size,
  pg_size_pretty(pg_relation_size(relname::regclass)) AS table_size,
  pg_size_pretty(pg_total_relation_size(relname::regclass) - pg_relation_size(relname::regclass)) AS index_size
FROM
  pg_stat_user_tables
ORDER BY
  pg_total_relation_size(relname::regclass) DESC
LIMIT 10;

```

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/tasks/query_table_schema.sql
> +  table_name = :table_name;
pgformatter removes the extra spaces
```suggestion
SELECT
  table_name,
  column_name,
  data_type
FROM
  information_schema.columns
WHERE
  table_name = :table_name;

```

2023-06-20 19:59 UTC, rose-huang commented on postgres_admin_panel/README.md
> +- To configure who is able to approve database queries other than `SELECT` queries, learn more about the [approvals](https://docs.airplane.dev/tasks/approvals) in Airplane.
also leave a comment that you can configure this in the query_database.airplane.ts file

2023-06-20 20:48 UTC, kkoppenhaver commented on postgres_admin_panel/postgres_admin_panel.airplane.tsx
> +        {output &&
Handled by using showNotification instead of `console.log` in useTaskMutation and then hiding the output table if there was an error.

```
onError: (error) => {
      showNotification({
        message: error,
        type: "error",
      });
      hideQueryTable = true;
    },
```

2023-06-20 22:14 UTC, rose-huang approved these changes
Just pushed a change to fix error handling for the prompt cancellation 
- showing the notification with error.error because error is an object with a field called "error"
- only showing the table if output.error is null because I think it still tries to display it if you try to set the variable for showing the table to false in the `onError`
- also got rid of the pg-query-emscripten from dev dependencies because @types/pg-query-emscripten isn't a real package. Not sure if there's a way to get rid of the small type hint in the import but I think that's fine

2023-06-21 13:21 UTC, merged