New template: Deployment pipeline dashboard
airplanedev/templates pull request #103
Opened 2023-06-07 16:26 UTC by kkoppenhaver

This template looks at a repo's releases and GH Actions runs to show a dashboard of recent releases, allows a user to create a new release and allows a user to rollback the latest release.

<img width="1728" alt="Screenshot 2023-06-07 at 11 06 04 AM" src="https://github.com/airplanedev/templates/assets/2965444/24c844f6-13ea-490c-81d4-59806b41f8a2">

2023-06-07 17:41 UTC, leeweisberger requested changes
Will take a look again when i can run the view without an error!

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +  };
Define these outside of the component

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +  const repoName = useComponentState("repoName");
Use generics to type the component state

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +    enabled: false,
Maybe leave a comment why this is not enabled? In general I don't think we should be afraid to comment up these templates

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      </Stack>
Any reason you aren't using a [form](https://docs.airplane.dev/views/form#basic-usage) for this?

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Callout
we should probably use a [description list](https://docs.airplane.dev/views/description-list) for this instead of trying to build out ourselves? Unless you have a good reason to build it yourself

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            <strong>Version:</strong> {output.release_data.version}
I get an error when running this view
<img width="458" alt="image" src="https://github.com/airplanedev/templates/assets/6363419/6740ca3a-b9ef-4d65-834f-63bbd49ed649">

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +                cancelText: "Cancel",
Is this the default cancelText?

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +  // function will be called.
Delete this comment I think

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +    run_data = run_data.map((obj) => {
You can do thisi n one line

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +    const workflow_runs = await octokit.rest.actions.listWorkflowRunsForRepo({
Use `camelCase` for javascript

2023-06-07 17:41 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +        display_title: obj.display_title,
Same everywhere. All `camelCase`

2023-06-07 20:56 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      </Stack>
I did it this way so I could access the values independently. When I was using a form, I had difficulty populating the Task params with the different form values, etc.

2023-06-07 21:09 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Callout
And I was using a <Link> component for the `releasedBy` and `viewRelease` portions, which I don't think I can do inside a DescriptionList?

2023-06-07 21:35 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            <strong>Version:</strong> {output.release_data.version}
This may have been from an old deploy or something? 

repoOwner: `kkoppenhaver`
repoName: `node-with-tests`

2023-06-07 22:15 UTC, leeweisberger requested changes
Going to get some design feedback from @trijeetm as well...

2023-06-07 22:15 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      </Stack>
In fact, we should be able to use a Task-backed form right? https://docs.airplane.dev/views/form#taskbacked-forms 

That should make the code simpler and look a bit nicer

2023-06-07 22:15 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +                { term: "Version", description: output.releaseData.version },
The view is crashing when I don't have access to a repo with this line. We should gracefully handle errors with a UI rather than crashing

2023-06-07 22:15 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +  async (params) => {
I know it's a bit more work, but we should really get these templates to work even if you don't configure the GH api to work. 

See https://www.notion.so/airplanedev/Template-Gallery-how-to-contribute-53af3baef69d40f29a737c0c2522a7c7?pvs=4#2c5428c0ef6244d582f398f6e75c8279

We should return hardcoded data if there is no access token provided so that the template still functions properly without hooking up to github

2023-06-07 22:16 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            <strong>Version:</strong> {output.release_data.version}
Yeah that works. Left a comment elsewhere, but if I try to access a repo that I haven't given my key access to, it should gracefully error and not crash

2023-06-07 22:18 UTC, rose-huang commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Callout
you should be able to use custom components inside of a description list!

2023-06-07 22:19 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Callout
I also am not sure why this is in a callout, but going to let @trijeetm talk to that!

2023-06-12 15:30 UTC, joshma submitted a review, later dismissed

2023-06-12 15:30 UTC, joshma commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +        <Stack spacing="xl" align="center" direction="row" justify="start">
IMO you should just take in a single repo field, format of `owner/name` (maybe set placeholder text or pick an interesting default value so users know)

2023-06-12 15:30 UTC, joshma commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Button onClick={refetch}>Submit</Button>
"Submit" feels a bit stodgy, maybe "Go"?

2023-06-12 15:30 UTC, joshma commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            <Heading level={2}>Create a new deployment</Heading>
Is it deployment or release? We should be consistent - `Create a new release`?

2023-06-12 19:47 UTC, rose-huang commented on deployment_pipeline_dashboard/README.md
> +# Template: Deployment pipeline dashboard
I don't think we typically put details on the dashboard here but instead put descriptions in `docs` for the template gallery

2023-06-12 20:24 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      </Stack>
> Why can't you get the values of the form?

@kellymtrinh helped me debug this issue on Thursday. The problem was that useTaskQuery wasn't able to pull the values, while useTaskMutation was.

I'll convert this to a task-backed form and figure out how we can use the output to power the table and release info down below.

2023-06-12 20:25 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +          <Callout
Makes sense, thanks for the feedback y'all. Based on some feedback from @trijeetm and some help from @kellymtrinh I was able to get this sorted in a way that makes sense. I do have a callout-related bug that I will put together a very basic repro case for.

2023-06-12 20:28 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/README.md
> +# Template: Deployment pipeline dashboard
👍 Noted, I'll make sure the description makes it into the docs.

2023-06-13 14:51 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      </Stack>
@leeweisberger Looking further, the reason that I didn't have this as task-backed was because of this example here: https://docs.airplane.dev/views/form#calling-a-task-with-usetaskmutation

Is it possible with a task-backed form to then use the output (because we need to display the table down below once the form is submitted)? Because the Form and the Table are two different components, I thought we had to use the useTaskMutation option.

2023-06-13 16:18 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +  async (params) => {
We now return sample data if repo information isn't passed in or if there's no GH access token provided.

2023-06-13 16:18 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +                { term: "Version", description: output.releaseData.version },
I believe the sample data return just added should fix this.

2023-06-14 15:22 UTC, leeweisberger requested changes

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +        <Stack width="full" grow>
Does the width full grow thing do anything? I don't think so?

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            className="stack-class"
What is this?

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +              { term: "View Release:", description: output.releaseData.url },
Let's put this in a link

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            title="Deployments"
What's the difference between a deployment and a release? Are they the same thing? If so can we use the same language?

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +    },
When i run this in studio without adding this token, I get:
<img width="1504" alt="image" src="https://github.com/airplanedev/templates/assets/6363419/3b6f960a-7383-4748-baf1-ef096e9e1bbc">

Check out the other templates that use hard coded data. You have to comment this out and include instructions on how to comment it back in, both here and to the readme

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +    if (!repoOwner || !process.env.GITHUB_ACCESS_TOKEN) {
Shouldn't there be an error if there's no repoOwner? This is not the same as not adding an access token

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +      const workflowRuns = await octokit.rest.actions.listWorkflowRunsForRepo({
What is a workflow run? This might be the correct thing to show, but without explanation or investigation of the github docs I don't know what this is :/

2023-06-14 15:22 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +    slug: "demo_create_release",
When I run this task I get an error:

<img width="650" alt="image" src="https://github.com/airplanedev/templates/assets/6363419/3171c1d9-7fcb-466a-b5cd-29d18e5c1957">

2023-06-14 16:23 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +        <Stack width="full" grow>
This was related to layout debugging that Kelly and I were doing. I'll remove it.

2023-06-14 16:23 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +            className="stack-class"
This was related to layout debugging that Kelly and I were doing. I'll remove it.

2023-06-14 17:13 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +      const workflowRuns = await octokit.rest.actions.listWorkflowRunsForRepo({
Adding a comment to provide some more explanation.

2023-06-14 17:29 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +    slug: "demo_create_release",
I this was a discrepancy between what was checked into version control vs deployed to the demo account. Re-running a deploy now.

2023-06-14 17:37 UTC, kkoppenhaver commented
Deployed the latest to the demo account here: https://app.airplane.dev/views/vew20230607z6v72fdb6nk?__env=prod

2023-06-14 18:14 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +    slug: "demo_create_release",
I'm running this locally. I still get this error...

2023-06-14 19:09 UTC, rose-huang requested changes

2023-06-14 19:09 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +          publishedBy: "johndoe",
it's slightly weird that johndoe is an actual person on GitHub. Maybe we should use octocat?

2023-06-14 19:09 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +      release_name: {
Feels a bit weird that this requires a release name and description but when we get the releases and show them in the table, there is no name or description

2023-06-14 19:09 UTC, rose-huang commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +    slug: "deployment_pipeline_dashboard",
prepend demo_

2023-06-14 19:09 UTC, rose-huang commented on deployment_pipeline_dashboard/create_release.airplane.tsx
> +    slug: "create_release",
this should also have demo_ prepended to it. But it's weird to have a task AND a view both named "Create release" with the same slug. can we rename this to "Create release form" or something more indicative of it being a view? rename filename and view name as well

2023-06-14 19:09 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +import airplane from "airplane";
these filenames don't need to have demo in them, just the slugs for the tasks

2023-06-15 14:18 UTC, leeweisberger commented on deployment_pipeline_dashboard/tasks/demo_get_release_and_run_data.airplane.ts
> +          publishedBy: "johndoe",
Yeah forgot to mention that. let's not link to the real user

2023-06-16 22:57 UTC, joshma reviewed
@kkoppenhaver - moving forward, I'm going to have @rose-huang replace me for signoff, so you'll just need her approval instead :)

2023-06-20 04:44 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +      release_name: {
From the looks of the GH API, we have two options. Do you have an opinion on which would be better?

  - Grab release-specific data inside the map function that generates the data from the table and output it as part of the table data. (From what I can tell, the listReleases endpoint doesn't output title/description so we would have to make each of these an individual API call, which doesn't seem great).
  - Make the release name/description optional params, since all we actually need is a tag number. (This feels like it doesn't actually solve the problem you're presenting...)

2023-06-20 16:55 UTC, rose-huang approved these changes
A few nits but overall looks really great!

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
we don't typically commit .gitignore files, remove this

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/README.md
> +- Once you have your PAT from GitHub, store it the `github_access_token` [config variable](https://docs.airplane.dev/platform/configs). This will ensure that both the Tasks that need to interact with
```suggestion
- Once you have your PAT from GitHub, store it the `github_access_token` [config variable](https://docs.airplane.dev/platform/configs). This will ensure that both tasks that need to interact with GitHub have access to the proper credentials.
```

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/README.md
> +- Remove mock data from the `demo_get_release_and_run_data.airplane.ts` task and remove the empty return statements from the `demo_create_release.airplane.ts` and `demo_rollback_release.airplane.ts`
update these filenames to remove "demo"

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      View Release
```suggestion
      View release
```

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/deployment_pipeline_dashboard.airplane.tsx
> +      View Run
```suggestion
      View run
```

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/get_release_and_run_data.airplane.ts
> +    name: "Get release and run data",
Can we add descriptions to the tasks themselves for this and the other 2?

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/rollback_release.airplane.ts
> +        description: "The ID of the release to be deleted",
```suggestion
        description: "The ID of the release to be rolled back",
```

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/create_release.airplane.ts
> +        description: "The name of the release.",
delete the periods in the parameter descriptions to be consistent?

2023-06-20 16:55 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +      release_name: {
Can we grab the title and description for the latest release and display those in the description list? and let's make the release name and description optional as well

2023-06-20 17:58 UTC, kkoppenhaver commented on deployment_pipeline_dashboard/tasks/demo_create_release.airplane.ts
> +      release_name: {
Can do!

2023-06-20 18:02 UTC, kkoppenhaver commented
Regarding the failing types, it seems like this is a recurring bug in octokit, which we use to interface with the GH REST API: https://github.com/octokit/types.ts/issues/534

2023-06-20 18:03 UTC, merged

2023-06-20 18:05 UTC, rose-huang commented on deployment_pipeline_dashboard/tasks/get_release_and_run_data.airplane.ts
> +      console.log(release.data);
@kkoppenhaver can we remove this console log? Thanks :)