Add AI database explorer template
airplanedev/templates pull request #108
Opened 2023-06-19 17:34 UTC by kkoppenhaver

2023-06-27 15:40 UTC, rose-huang requested changes

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +      `select
@ericliuche can you take a quick look at this and the prompt below for any thoughts? I know eric has been returning the table name with the columns and their types when describing resources for autopilot so that the queries are less likely to be hallucinated

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +      return await airplane.ai.chat(
can we check that the output of airplane.ai.chat is a query and if not, return an error? so we don't have the ai return the error message into the query box, which feels weird

![Screenshot 2023-06-27 at 11 26 17 AM](https://github.com/airplanedev/templates/assets/34196250/909e15d7-58b6-465e-9ed3-e493d8a5b540)

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    slug: "ai_database_explorer",
prepend demo to slug

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +const AiDatabaseExplorer = () => {
nit 
```suggestion
const AIDatabaseExplorer = () => {
```

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +        >
just curious - why are we using useTaskMutation with the form instead of using a task backed form? for both this and the other one?

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +          {queryOutput &&
I would expect this table not to be shown if I have generated a new query

right now if I do:
- ask a question, submit form to generate a select query
- submit second form to run select query, see table in output
- ask another question, submit form to generate a select query
the output from the first query is not cleared

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +          {queryError && (
It's still trying to show a table even if my select query is invalid

![image](https://github.com/airplanedev/templates/assets/34196250/05bd9bc0-f63b-4b47-ba75-222111ac0397)

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    loading: queryParsing,
can we handle the case when the first task to generate the select query errors?

2023-06-27 15:40 UTC, rose-huang commented on ai_database_explorer/README.md
> +- If you plan on using a [database resource](https://docs.airplane.dev/resources/overview) other than the demo database, change the `demo_db` resource in `run_select_query.airplane.ts` to the slug of
should also change demo_db in the other task too

2023-06-27 20:01 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    slug: "ai_database_explorer",
Sorry, I thought I caught all of these. Adding to my notes that Views need `demo_` as well.

2023-06-28 03:06 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +          {queryError && (
This has been fixed. It should now return an error of "Only SELECT-type queries are allowed. Please provide a different query."

<img width="1381" alt="Screenshot 2023-06-27 at 10 06 48 PM" src="https://github.com/airplanedev/templates/assets/2965444/c8720f52-fbb5-4c29-901c-a2e4d5729156">

2023-06-28 04:19 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +          {queryOutput &&
This flow now works. Going to leave an additional question as a comment on this PR.

2023-06-28 04:20 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    loading: queryParsing,
This is now handled

<img width="1389" alt="Screenshot 2023-06-27 at 11 20 19 PM" src="https://github.com/airplanedev/templates/assets/2965444/403a057f-8e6b-4f40-9124-be493c85451a">

2023-06-28 04:29 UTC, kkoppenhaver commented
@rose-huang I addressed the changes noted above, but I had a question that I couldn't quite work through.

We need to pass the result of the first task-backed form to the second form. I attempted to do that using the `setValue` function of `useComponentState`.

```
const { value: queryFormQuery, setValue: setQueryFormQuery } =
    useComponentState("queryForm.query");
```

However, I noticed when the second form was conditionally rendered, the setValue call would fail to set the value. As soon as I made the second form always visible, the setValue worked correctly.

I'm not sure if this is a property of React that I'm not familiar with or something, but for now, I have the second form always visible so that it works. If a query hasn't been generated, the submit button of the second form is disabled.

Do you have any recommendations on how to make the second form conditionally render while still having the ability to pass the result of the first Task into it using setValue?

2023-07-05 22:53 UTC, rose-huang requested changes

2023-07-05 22:53 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +  const [queryRunning, setQueryRunning] = useState(false);
I don't think we need these, I think the form already handles submit loading state

2023-07-05 22:53 UTC, rose-huang commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +          `Your question could not be parsed into a query. Please modify your question or try again later.`
```suggestion
          `Your question could not be parsed into a SQL query. Please modify your question or try again later.`
```

2023-07-05 22:53 UTC, rose-huang commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +    } catch (error) {
when do we hit this error? when `airplane.ai.chat` errors? should we have a different error message

2023-07-05 22:53 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    useComponentState("queryForm.query");
> Do you have any recommendations on how to make the second form conditionally render while still having the ability to pass the result of the first Task into it using setValue?

instead of using component state, you can do 
```
  const [queryFormQuery, setQueryFormQuery] = useState("");
```

and on line 60 have
```
      {!parseError && queryFormQuery && (
```

and set the defaultValue: queryFormQuery for the query in the field options of the second form

2023-07-05 22:53 UTC, rose-huang commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +          `Your question could not be parsed into a query. Please modify your question or try again later.`
can we just use normal quotes for all of the cases where we dont need backticks.. here and in other errors

2023-07-06 03:47 UTC, kkoppenhaver commented on ai_database_explorer/tasks/parse_language_into_query.airplane.ts
> +    } catch (error) {
Yes, I put this in there because there were a couple times in my testing where OpenAI timed out I think? So I wanted to catch those cases.

2023-07-06 03:57 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +    useComponentState("queryForm.query");
Awesome, thank you!

2023-07-06 20:52 UTC, rose-huang approved these changes
Looks great!

2023-07-06 20:52 UTC, rose-huang commented on ai_database_explorer/tasks/run_select_query.airplane.ts
> +        );
same for above error
```suggestion
          "Only SELECT-type queries are allowed. Please provide a different query."
        );
```

2023-07-06 20:52 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +            disabled={queryFormQuery === ""}
nit: I think we can probably just remove this? the form will not submit if the field is empty string anyway. or at least make this consistent with the first form, where the button is currently not disabled even if the natural language query is empty

2023-07-06 20:52 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +  const [queryFormQuery, setQueryFormQuery] = useState("");
Sorry I know I suggested this naming but perhaps something like `queryFormDefaultQuery` and `setQueryFormDefaultQuery` would be better

2023-07-06 20:52 UTC, rose-huang commented on ai_database_explorer/tasks/run_select_query.airplane.ts
> +        description: "A query you want to run against your database resource",
nit: let's give this a period? I'm not sure if we have standardized period vs no period but the other form uses punctuation

2023-07-06 20:54 UTC, rose-huang commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +              fieldOptions: [{ slug: "query", defaultValue: queryFormQuery }],
@geodn do we support custom components for parameters in task backed forms? would be nice if we could have a code block with syntax highlighting 
<img width="1401" alt="Screenshot 2023-07-06 at 4 54 35 PM" src="https://github.com/airplanedev/templates/assets/34196250/890b79a4-bcae-4178-a014-2ecb17d423f8">

2023-07-08 15:38 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +            disabled={queryFormQuery === ""}
Agreed, I think this was a relic of the form previously not being task-backed.

2023-07-08 16:05 UTC, kkoppenhaver commented on ai_database_explorer/ai_database_explorer.airplane.tsx
> +              fieldOptions: [{ slug: "query", defaultValue: queryFormQuery }],
Not quite sure what's going on here. I'm able to see syntax highlighting in that field.

<img width="1444" alt="Screenshot 2023-07-08 at 11 04 16 AM" src="https://github.com/airplanedev/templates/assets/2965444/68ca7069-9078-4b1f-abe4-db3c036b68f8">

2023-07-11 13:57 UTC, merged