Add PDF parser template
airplanedev/templates pull request #115
Opened 2023-06-30 14:40 UTC by kkoppenhaver

Original spec: https://www.notion.so/airplanedev/Data-entry-from-PDFs-f2d487fc14c848d0a04d6a2bbbdadd25

Keeping this one pretty simple as some of our other AI templates have gotten a bit complex. This is a single task that takes a file input as a param and returns a table of the structured data.

2023-07-17 23:48 UTC, calufornia requested changes
Looking good—mostly just some phrasing suggestions

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/pdf_parser.airplane.ts
> +      number should be formated correctly with dashes (XXX-XX-XXX).
```suggestion
      number should be formatted correctly with dashes (XXX-XX-XXX).
```

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/pdf_parser.airplane.ts
> +    //   NOTION_DB_ID: { config: "notion_db_id" },
Remove these

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/pdf_parser.airplane.ts
> +      // If the OPENAI_API_KEY is not set, we want to give some output
```suggestion
      // If OPENAI_API_KEY is not set, return the output of the scraped PDF.
```

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/README.md
> +- Uncomment `OPENAI_API_KEY` environment variable in the `pdf_parser.airplane.ts` task.
```suggestion
- Uncomment the `OPENAI_API_KEY` environment variable in the `pdf_parser.airplane.ts` task.
```

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/pdf_parser.airplane.ts
> +    // OPENAI_API_KEY: { config: "openai_api_key" },
```suggestion
    //     OPENAI_API_KEY: { config: "openai_api_key" },
```
Indent this so that when it's uncommented, the indentation is correct

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/README.md
> +- Once you have your API key from OpenAI, store it the `openai_api_key` [config variable](https://docs.airplane.dev/platform/configs). This will ensure that the task that needs to interact with OpenA
```suggestion
- Once you have your API key from OpenAI, store it in a [config variable](https://docs.airplane.dev/platform/configs) named `openai_api_key`. This will ensure that the task has the proper credentials it needs to interact with OpenAI.
```

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/README.md
> +- Also add the config variable to your dev config file in order to [develop tasks locally](https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable).
```suggestion
- Also add the config variable to your [dev config file](https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable) to develop the task locally.
```

2023-07-17 23:48 UTC, calufornia commented on pdf_parser/README.md
> +- Once you have your API key from OpenAI, store it the `openai_api_key` [config variable](https://docs.airplane.dev/platform/configs). This will ensure that the task that needs to interact with OpenA
Can we capitalize the config variable name? I think for most of the other templates, we've standardized on all caps for both the config + env var name, e.g. https://github.com/airplanedev/templates/blob/407cfebd7559e2c1103bf13f1e8e8ae5b87624ae/support_ticket_dashboard/tasks/create_linear_issue.airplane.ts#L49

2023-07-18 16:58 UTC, kkoppenhaver commented on pdf_parser/pdf_parser.airplane.ts
> +    //   NOTION_DB_ID: { config: "notion_db_id" },
I think we should leave these in because they're part of the Notion portion. I'll call them out in the README

2023-07-18 16:59 UTC, kkoppenhaver commented on pdf_parser/pdf_parser.airplane.ts
> +    //   NOTION_DB_ID: { config: "notion_db_id" },
Nevermind, I was mistaking this for another template. Removed.

2023-07-19 02:18 UTC, calufornia approved these changes
Nice job!

You can do it in this PR or a different one, but can you also change the config variables [here](https://github.com/search?q=repo%3Aairplanedev%2Ftemplates+openai_api_key&type=code) to also follow the all caps format?

2023-07-19 02:18 UTC, calufornia commented on pdf_parser/README.md
> +- Remove the early return statement from the `pdf_parser.airplane.ts` task.
```suggestion
- Remove the early return statement from the `pdf_parser.airplane.ts` task.
```
This is unnecessary right? Like once `token` is non-empty, we won't hit the return statement anyway.

2023-07-19 02:18 UTC, calufornia commented on pdf_parser/pdf_parser.airplane.ts
> +    // set the environment variable.
```suggestion
    // Return if OPENAI_API_KEY is not set.
```
Same comment as above

2023-07-19 17:03 UTC, merged