Template database backup
airplanedev/templates pull request #127
Opened 2023-07-28 22:09 UTC by kkoppenhaver

Notion spec: https://www.notion.so/airplanedev/Template-Database-backup-tool-85607fbf443b48eaa25456b3f3d0d8f2

This creates a template that backs up a specific database table and pushes that backup to S3.

2023-07-28 22:25 UTC, kkoppenhaver commented on database_backup/database_backup.sh
> +DB_HOSTNAME=$(jq -r '.db.host' <<<"$AIRPLANE_RESOURCES")
Is this the right way to be pulling in these variables? I thought there would be an easier way to do that, but couldn't find anything in the docs.

2023-07-31 22:42 UTC, colinking requested changes
Looks good!

2023-07-31 22:42 UTC, colinking commented on database_backup/.metadata/metadata.json
> +  "visualDescription": "This tool allows a user to specifiy a name for the backup file to be generated. It then runs, creates the backup and uploads the resulting .zip file to AWS S3.",
What's the difference between a visual description and a normal description?

2023-07-31 22:42 UTC, colinking commented on database_backup/.metadata/metadata.json
> +      "fileName": "/database_backup.sh"
Why does this point at the `.sh` file instead of the `.task.yaml`? What you have looks to match what we do elsewhere. Just curious.

2023-07-31 22:42 UTC, colinking commented on database_backup/.metadata/metadata.json
> +  "name": "Database backup",
Do we have any advice on naming? e.g. `Database backup` vs. `Backup database`. IMO, I like the latter more because it describes the action that the task performs (rather than the artifact it creates).

2023-07-31 22:42 UTC, colinking commented on database_backup/.metadata/metadata.json
> +      "name": "Docker-based environments",
eh? Just not to confuse "environments" with the product feature

```suggestion
      "name": "Custom Dockerfile",
```

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.task.yaml
> +    required: false
Did you want to add a schedule here? Only because you mentioned it in the `metadata.json` file.

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.task.yaml
> +      config: AWS_BUCKET
Let's make the region configurable, too. That can just be a `value` instead of a `config` IMO.

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.task.yaml
> +      config: AWS_BUCKET
Should `AWS_BUCKET` be a `value` instead? Since it's not a secret and might not be shared with other tasks. I don't feel strongly FWIW.

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.task.yaml
> +  db: demo_db
Do we usually add comments, e.g.

```suggestion
  # Replace this with the slug of your DB resource.
  db: demo_db
```

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.sh
> +echo "Database backup performed successfully."
Thoughts on printing the AWS URL as a task output? That would also spruce up the image above, which looks fairly empty right now.

https://docs.airplane.dev/tasks/output#producing-output-from-tasks

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.sh
> +aws configure set default.region us-east-1
The AWS CLI will already look for these in the environment. You can remove these three lines and rename the env vars to match what AWS looks for: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

`AWS_ACCESS_KEY_ID` /  `AWS_SECRET_ACCESS_KEY` / `AWS_REGION`

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.sh
> +DB_HOSTNAME=$(jq -r '.db.host' <<<"$AIRPLANE_RESOURCES")
This looks right! Though I think this reads slightly better since it reads left-to-right:

```sh
DB_PORT=$(echo $AIRPLANE_RESOURCE | jq -r '.db.port')
```

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.sh
> +DB_HOSTNAME=$(jq -r '.db.host' <<<"$AIRPLANE_RESOURCES")
You could also link to the docs for this in a comment, though the docs are just about to move. The new URL will be here: https://docs.airplane.dev/reference/env-vars#resources

(You can preview here: https://docs-git-asm-512-docs-ia-project-final-go-live.airstage.app/reference/env-vars#resources)

2023-07-31 22:42 UTC, colinking commented on database_backup/README.md
> +- Visit the docs to learn more about how to build views: https://docs.airplane.dev/views/getting-started
This mentions Views not tasks

2023-07-31 22:42 UTC, colinking commented on database_backup/database_backup.task.yaml
> +name: Database backup
Let's add a task description

2023-07-31 22:42 UTC, colinking commented on database_backup/.metadata/metadata.json
> +  "description": "A tool that runs a database backup and uploads the backup to AWS S3.",
This only works with PostgreSQL, so IMO it should clarify that here.

2023-08-01 16:13 UTC, kkoppenhaver commented on database_backup/.metadata/metadata.json
> +  "name": "Database backup",
We don't have anything set in stone. Previous templates have included names like "PDF parser" and "Feature request ticket creator" which definitely focus on the action. I'm ok with Backup database here.

2023-08-01 16:18 UTC, kkoppenhaver commented on database_backup/.metadata/metadata.json
> +      "fileName": "/database_backup.sh"
It's so on the individual Template docs page it shows the Tasks in the sidebar, clicking on a Task name will swap the code display to the actual task itself vs the definition.

SQL example: 
<img width="1590" alt="Screenshot 2023-08-01 at 11 17 27 AM" src="https://github.com/airplanedev/templates/assets/2965444/08c28538-52ca-4ac2-a168-ac17fc3bc0f6">

2023-08-01 16:19 UTC, kkoppenhaver commented on database_backup/.metadata/metadata.json
> +      "name": "Docker-based environments",
👍 Good call

2023-08-01 16:21 UTC, kkoppenhaver commented on database_backup/.metadata/metadata.json
> +  "visualDescription": "This tool allows a user to specifiy a name for the backup file to be generated. It then runs, creates the backup and uploads the resulting .zip file to AWS S3.",
The visualDescription is intended to be helpful for Autopilot!

> Your metadata file should have _at minimum_ the following keys:
>
> - `name`: The name of your template!
> - `description`: A human-readable description of your template.
> - `visualDescription`: An extensive description of your template, intended for indexing the template in Autopilot.

2023-08-01 16:21 UTC, kkoppenhaver commented on database_backup/README.md
> +- Visit the docs to learn more about how to build views: https://docs.airplane.dev/views/getting-started
Updated

2023-08-01 16:25 UTC, kkoppenhaver commented on database_backup/database_backup.sh
> +DB_HOSTNAME=$(jq -r '.db.host' <<<"$AIRPLANE_RESOURCES")
Updated the syntax and added a comment linking to the docs.

2023-08-01 16:28 UTC, kkoppenhaver commented on database_backup/database_backup.task.yaml
> +  db: demo_db
We've gone back and forth on this, but I think it makes sense here.

2023-08-01 16:31 UTC, kkoppenhaver commented on database_backup/database_backup.task.yaml
> +      config: AWS_BUCKET
Sounds good to me 🙂

2023-08-01 16:44 UTC, kkoppenhaver commented on database_backup/database_backup.task.yaml
> +    required: false
Good call! Added. This will be a good example of how to use schedules.

2023-08-07 20:20 UTC, colinking approved these changes
Looks great! Nice job.

2023-08-07 20:20 UTC, colinking commented on database_backup/.metadata/metadata.json
> +  "description": "A tool that runs a PostgreSQL database backup and uploads the backup to AWS S3.",
```suggestion
  "description": "A tool that generates a PostgreSQL database backup and uploads it to AWS S3.",
```

2023-08-07 20:20 UTC, colinking commented on database_backup/.metadata/metadata.json
> +  "visualDescription": "This tool allows a user to specifiy a name for the backup file to be generated. It then runs, creates the backup and uploads the resulting .zip file to AWS S3.",
```suggestion
  "visualDescription": "This tool allows a user to specify a name for the backup file to be generated. It then runs, creates the backup and uploads the resulting .zip file to AWS S3.",
```

2023-08-07 20:20 UTC, colinking commented on database_backup/README.md
> +- You'll need to get a access key and secret from your AWS Account. Once you have done this, store them in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` config variables. You should also modify
```suggestion
- You'll need to get a access key and secret from your AWS Account. Once you have done this, store them in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` config variables. You should also modify the `AWS_REGION` and `AWS_BUCKET` environment variables to specify your AWS region and S3 bucket name. 
```

2023-08-07 20:20 UTC, colinking commented on database_backup/README.md
> +- You'll need to get a access key and secret from your AWS Account. Once you have done this, store them in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` config variables. You should also modify
```suggestion
- Get an access key and secret from your AWS account. Once you have done this, store them in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` config variables. You should also modify the `AWS_REGION` and `AWS_BUCKET` environment variables to store your default region and bucket name. 
```

2023-08-07 20:20 UTC, colinking commented on database_backup/README.md
> +- Also add the config variable to your dev config file in order to [develop tasks locally](https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable).
```suggestion
- [Define these config variables in Studio](https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable) in order to develop this task locally.
```

2023-08-07 20:20 UTC, colinking commented on database_backup/database_backup.sh
> +echo "airplane_output_set ${data}"
You can output specific keys directly:

```suggestion
echo "airplane_output_set:URL \"https://${AWS_BUCKET}.s3.amazonaws.com/${filename}\""
```

2023-08-07 20:20 UTC, colinking commented on database_backup/database_backup.task.yaml
> +description: "Shell task that runs a PostgreSQL database backup and uploads the backup to AWS S3."
```suggestion
description: "Generates a PostgreSQL database backup and uploads it to AWS S3."
```

2023-08-07 20:20 UTC, colinking commented on database_backup/database_backup.task.yaml
> +      value: us-east-2
Let's configure this with the most common AWS region.

```suggestion
      value: us-east-1
```

2023-08-07 21:25 UTC, merged