Create monitor and alert on database template
airplanedev/templates pull request #2
Opened 2022-09-08 17:16 UTC by zhan-airplane

Basically just one task

2022-09-08 21:54 UTC, rose-huang requested changes
Thanks so much for working on this Zhan!! 

For this template, maybe we need a tsconfig? @colinking are we still adding a tsconfig on init for ts tasks?

2022-09-08 21:54 UTC, rose-huang commented on database_issues_alert/alert_on_database_issues.ts
> +  if (percentTowardsWraparound > wraparoundThresholdPercent) {
Can we make sure this task still works if a user just clones it and runs `airplane dev` on the task without having a slack channel set up? Maybe the slack param can be optional and it will console log a message if the slack channel param is empty?

2022-09-08 21:54 UTC, rose-huang commented on database_issues_alert/alert_on_database_issues.task.yaml
> +# Full reference: https://docs.airplane.dev/tasks/task-definition
Let's delete all the fields that aren't being used and extra comments (except for the full reference comment) so this looks cleaner - like https://github.com/airplanedev/templates/blob/main/getting_started/tasks/list_accounts.task.yaml

2022-09-08 21:54 UTC, rose-huang commented on database_issues_alert/README.md
> +- Edit the slack channel you want to send the alert to in alert_on_database_issues.task.yaml (where it says `INSERT_SLACK_CHANNEL_HERE`)
we should assume that the user just made an airplane account and doesn't have anything set up yet. probably should have a step to integrate slack (if they haven't already)

2022-09-08 21:57 UTC, colinking commented
Yep, @ameyakhare is actually working on that this cycle.

2022-09-08 21:58 UTC, rose-huang commented on database_issues_alert/alert_on_database_issues.ts
> +// Put the main logic of the task in this function.
nit: remove comment

2022-09-09 16:13 UTC, rose-huang approved these changes
Looks awesome, ty zhan!!

2022-09-09 16:13 UTC, rose-huang commented on database_issues_alert/README.md
> +- If you plan on using this on a different database resource than the demo database, change the `demo_db` resource in alert_on_database_issues.task.yaml to your own database resource's slug.
lol super nit: can we remove the period at the end of this bullet point?

2022-09-09 16:16 UTC, merged