Use charts in customer insights dashboard
airplanedev/templates pull request #20
Opened 2022-10-06 00:04 UTC by geodn

Switch to charts to showcase chart functionality, and also the data doesn't look very nice in tables.

Deployed version: https://web.airstage.app/views/vew20220914z6hfn588ya3?__env=prod

2022-10-06 15:12 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          <Chart
nit: can you make the order axis start from 0 and not have decimals?

2022-10-06 15:13 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
not related to this PR but can we rename this title to Customer insights dashboard?

2022-10-06 15:13 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>            title="Top products"
maybe this could be a bar chart? wdyt

2022-10-06 15:14 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          outputTransform={(o) => o.Q1}
should we make SQL tasks work without output transform in charts like it works for tables? @zhan-airplane cc @stepzhou

2022-10-06 15:15 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
or like... add a h1 title for Customer insights dashboard and make Global stats and Customer details an h2 or h3 or whatever size looks best

2022-10-06 23:31 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          <Chart
I don't think we actually support changing the tick spacing/range. It's possible to remove the decimals, but then you have 0/1/1/2 instead of 0/0.5/1/1.5 lol... cc @zhan-airplane

2022-10-06 23:40 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          outputTransform={(o) => o.Q1}
I left this feedback for Zhan, he said he'll implement it next week 👍

2022-10-06 23:45 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>            title="Top products"
Great idea, updated

2022-10-07 00:14 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
Personally I think "customer insights dashboard" doesn't add a lot to clarify the content, and we're not really surfacing a lot of insights 😅 Synced with Trijeet and I think we have a mild preference toward just keeping it as Global Stats, since it describes the content.

2022-10-07 15:11 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
If we don't think we're surfacing insights, should we rename the template? I think having the title of the template in the view or something similar would make it look more consistent in screenshots with the other templates and also make it more clear what the template is when we don't have the title underneath it (ie in the docs homepage)


<img width="1201" alt="image" src="https://user-images.githubusercontent.com/34196250/194586691-5ce9a806-cf98-4f9f-8d05-ca8e0100bcec.png">

2022-10-07 15:12 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
Like in this image - if I was looking for this template, I would probably control + f for a template called "Global stats" 


<img width="1175" alt="image" src="https://user-images.githubusercontent.com/34196250/194587056-43703e1b-9d3d-4825-bfa3-fbca95751a29.png">

2022-10-07 18:06 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
Chatted with cc @trijeetm (feel free to chime in with additional thoughts) about a few possible options:

- could change this banner to have three different images (each linking to a different template)
- could rename the template
- could change the title to customer insights
  - could optionally add subheadings
- could keep as is

I think the cleanest option is to make the banner have 3 different options, linking to the specific templates. It's an improvement in and of itself, but it also allows us to decouple the template contents from the template title. Technically it is "customer insights" (though the insightfulness can be debated) so it would fit as a title, but then with the subheadings it might look kinda cluttered. What do you think of that change?

2022-10-07 18:14 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
Clicking on different parts of the image to go to each template feels a bit off and unexpected to me, UX wise. I don't think the 3 templates "image" should function as a browser if it looks like an image. We don't link to something different if you click on the image for any of the other LinkTiles in docs. The LinkTile also has this group hover functionality where if you hover over any part of the component, it will add the arrow next to "Browse template gallery" and also bold the text and we *could* change that for the templates but then it would be inconsistent with all the other LinkTiles. Happy to chat over slack about this with you and trijeet if you think that's easier  

I also don't think having subheadings would look cluttered, this is what kelly's template is doing - 
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/34196250/194623099-691b260e-3f55-4949-802a-c90675597cf0.png">

2022-10-07 18:19 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
>        <Title>Global stats</Title>
I just think templates feel more consistent and easier to identify if the view title more or less matches the title of the template - like in notion's template gallery https://www.notion.so/templates

I think the only time the notion template title is extremely different from the notion doc title is when there are multiple notion docs in a template

2022-10-07 18:44 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          <Chart
oh that is weird haha - file this feedback in linear?

2022-10-07 18:45 UTC, rose-huang commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          outputTransform={(o) => o.Q1}
this would be a breaking change, right? If so, we should include that update in this template before we merge in the charts

2022-10-11 10:53 UTC, zhan-airplane commented
FYI @rose-huang I merged charts docs last week https://docs.airplane.dev/views/chart

2022-10-11 21:17 UTC, rose-huang requested changes
RCing to continue discussion in the PR

2022-10-12 16:21 UTC, geodn commented on customer_insights_dashboard/customer_insights/customer_insights.view.tsx
> +          outputTransform={(o) => o.Q1}
Just chatted with Zhan. He says it'll take some time before he can get to this, and it won't be a breaking change. I suggest proceeding with this for now, since it'll be nice to showcase some of our charts 🙂

2022-10-12 21:36 UTC, rose-huang approved these changes
thanks for updating this with the charts + for updating the title! :)

2022-10-12 21:39 UTC, merged