Update command to develop templates
airplanedev/templates pull request #25
Opened 2022-10-17 16:02 UTC by calufornia

Updates all the `airplane views dev` commands to use `airplane dev` (we don't need the `--studio` flag since that will be the default). Also moves the "Deploy tasks" instructions to be alongside the "Deploy view" instructions, since deploying tasks is no longer necessary to develop the template locally.

Depends on https://github.com/airplanedev/cli/pull/732

2022-10-20 17:04 UTC, rose-huang requested changes

2022-10-20 17:04 UTC, rose-huang commented on admin_panel/README.md
>  - Deploy your view: `airplane deploy .`
I think we could actually just deploy it all together using `airplane deploy . --yes` instead of deploying tasks separately? seems like we can get rid of the `airplane deploy tasks --yes` step

2022-10-24 22:58 UTC, calufornia commented on admin_panel/README.md
>  - Deploy your view: `airplane deploy .`
Changed everything to `airplane deploy --yes` - I think that's equivalent to `airplane deploy . --yes`

2022-10-24 23:08 UTC, calufornia commented on github_pr_dashboard/README.md
> +  - Also add the config variable to your dev config file in order to develop tasks locally: https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable
@rose-huang I also added instructions on using a local config variable to a couple places that were missing it

2022-10-24 23:09 UTC, calufornia commented on github_pr_dashboard/README.md
> +  - Also add the config variable to your dev config file in order to develop tasks locally: https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable
I think we still need the instruction above this (on creating the config variable in prod) because they'll need it when they deploy their task to prod

2022-10-25 15:39 UTC, rose-huang approved these changes
💯

2022-10-25 15:39 UTC, rose-huang commented on support_ticket_dashboard/README.md
> +- Deploy your tasks and view: `airplane deploy --yes`
nit: maybe this should be back at the bottom of the instructions after the api key stuff like it is for the other templates

2022-10-26 01:44 UTC, calufornia commented on github_pr_dashboard/README.md
> +  - Also add the config variable to your dev config file in order to develop tasks locally: https://docs.airplane.dev/dev-lifecycle/dev-config-file#add-a-config-variable
yes! that's up next on the roadmap

2022-10-26 02:23 UTC, merged