Feature flagging template
airplanedev/templates pull request #28
Opened 2022-10-26 16:56 UTC by benedictgeek

To test:

`cd feature_flagging_dashboard`
run `npm install && airplane dev .`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/components/feature_customers.tsx
> +  { accessor: "customer_id", label: "Customer ID" },
Don't need to display the id columns

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "feature_id", label: "Feature ID" },
Don't need to display the ID column

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "feature_name", label: "Feature name" },
Can just call the column `Name`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "updated_at", label: "Last update", component: FormatDate },
Also should call the column `Last updated`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +        <Title order={5}>Do you want to delete this feature?</Title>
Could you instead put the `Delete` button next to the `Update` button? doesn't need to be in it's own section

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +          task={{
add `preset="secondard"`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +          Delete feature
Rename to `Delete`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +              label="Enable?"
rename to `Enabled`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +        </Stack.Item>
Could you actually make the button show a `Dialog` instead of a card? it's a bit less intrusive and also allow you to close the dialog if you decide not to make a new feature

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/components/feature_customers.tsx
> +const AddCustomerToFeature = ({ searchKeyword, selectedFeature }) => {
Could you make this component always show the add customers section and not hide it behind a button? also make the `Select customer` dropdown smaller and inline with the `Search` button kind of like how it looks here
https://docs.airplane.dev/templates/github-pr-dashboard
<img width="571" alt="Screen Shot 2022-10-27 at 3 23 49 AM" src="https://user-images.githubusercontent.com/11494140/198217793-8e4549cd-6ded-4263-bf0d-5bab085cf99c.png">

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/components/feature_customers.tsx
> +              Add customer
rename to just `Add`

2022-10-27 07:31 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +      slug: searchFeaturesSlug,
this task doesn't seem to work in prod `https://app.airplane.dev/views/vew20221025zkwej1jms2c`, could you fix it?

2022-10-27 08:59 UTC, benedictgeek commented on feature_flagging_dashboard/feature_flagging/components/feature_customers.tsx
> +  { accessor: "customer_id", label: "Customer ID" },
Removing `feature_id` from the list as it is not needed but leaving `customer_id` since I will need this data to process the feature customer delete flow, however, I'm hiding it from view in the `hiddenColumns` table props

2022-10-27 09:02 UTC, benedictgeek commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "feature_id", label: "Feature ID" },
I will also be hiding this in the `hiddenColumns` table props because I will need the `feature_id` to query the `features_customers` table, or is there another way to get the `feature_id` if I didn't add it to the list of columns for the table?

2022-10-27 09:58 UTC, benedictgeek commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "feature_id", label: "Feature ID" },
Kindly disregard, found out I could just hide it using `hiddenColumns` table prop

2022-10-27 09:58 UTC, benedictgeek commented on feature_flagging_dashboard/feature_flagging/components/feature_customers.tsx
> +  { accessor: "customer_id", label: "Customer ID" },
Kindly disregard, found out I could just hide it using `hiddenColumns` table prop

2022-10-27 21:50 UTC, ericliuche reviewed
This looks awesome! Just a couple more comments and should be good to go

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +            sx={{ width: "150px" }}
use default width if it looks fine

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +                  customer.customer_id + " - " + customer.contact_name
just use the name, don't need to surface customer id

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +                feature_id: selectedFeature?.feature_id,
the `?.` might not be necessary, i think `selectedFeature` is non null

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +            onChange={(value) => setSelectedCustomer(value)}
can you use the Select component state here instead of using `selectedCustomer`?

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +      </Button>
Could you move this button into the same row? Also does the default button size look okay?

![image](https://user-images.githubusercontent.com/11494140/198399785-b09b00e0-fdd9-4ba7-9b5d-30275df5657a.png)

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +const EditFeature = ({ selectedFeature }) => {
actually instead of having a separate card with the edit feature, could we just edit the columns in line? delete can just but a row action inside the table. columns have a `canEdit` prop https://docs.airplane.dev/views/table#editing-rows

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +const CreateFeature = () => {
`CreateFeatureButton`

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +const FeatureCustomers = ({ selectedFeature }) => {
`CustomerFeaturesTable`

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/create_feature.sql
> +-- See SQL documentation: https://docs.airplane.dev/creating-tasks/sql
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/create_feature_customer.sql
> +--   customer_id;
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/customers_list.sql
> +-- See SQL documentation: https://docs.airplane.dev/creating-tasks/sql
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/delete_feature.sql
> +-- delete features customers
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/delete_feature_customer.sql
> +-- delete features customers
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/edit_feature.sql
> +-- See SQL documentation: https://docs.airplane.dev/creating-tasks/sql
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/search_feature_customers.sql
> +-- See SQL documentation: https://docs.airplane.dev/creating-tasks/sql
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/tasks/search_features.sql
> +-- See SQL documentation: https://docs.airplane.dev/creating-tasks/sql
delete comments

2022-10-27 21:50 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "feature_name", label: "Name" },
i just added a `features_description` column to the database, could you incorporate it?

2022-10-28 16:57 UTC, rose-huang requested changes

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/README.md
> +- Deploy your view: `airplane deploy .`
We don't need to deploy tasks first anymore 

replace with 
```
- Develop your template locally: `airplane dev`
- Deploy your tasks and view: `airplane deploy --yes`
```
and confirm that it works

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/search_features.task.yaml
> +name: Search features
Can we rename this to list features and get rid of the search keyword slug given that we aren't using it? 

also please rename the slug in this file, the entrypoint, remove the query args, change the file names, update the SQL query, and update the references in the view

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/search_feature_customers.task.yaml
> +# Full reference: https://docs.airplane.dev/tasks/task-definition
Can we rename this to "List feature customers" and get rid of the search keyword slug given that we aren't using it? 

also please rename the slug in this file, the entrypoint, remove the query args, change the file names, update the SQL query, and update the references in the view

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/search_feature_customers.task.yaml
> +description: "SQL task that shows all customers belonging to a feature that match a search keyword."
```suggestion
description: "Lists all customers with a particular feature enabled."
```

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/search_feature_customers.task.yaml
> +    description: The feature ID
nit: this description isn't really adding information, remove

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/edit_feature.task.yaml
> +    description: Boolean feild indicating whether a feature is enabled or not
nit: field

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/edit_feature.task.yaml
> +    description: The feature's description
remove descriptions that are just repeating the name - so remove description for feature_description, feature_name, and feature_id

same for other descriptions in other tasks

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/delete_feature_customer.task.yaml
> +name: Delete feature customer
Can we rename this to something more clear and update the description slug and file names? Ie "Disable feature for customer"? @ericliuche if you have any suggestions

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/customers_list.task.yaml
> +slug: demo_customers_list
let's call this "List customers" and revise the description. We aren't passing any search keywords

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/create_feature_customer.task.yaml
> +name: Create feature customer
I think a name like "Enable feature for customer" would be more clear - cc @ericliuche

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/create_feature.task.yaml
> +name: Create features
nit: change this to Create feature (singular instead of plural)

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/tasks/create_feature.sql
> +  updated_at;
Can you make sure all the SQL files have a newline at the end?

2022-10-28 16:57 UTC, rose-huang commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.yaml
> +entrypoint: feature_flagging.view.tsx
newline at the end

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +      <Text>Look up a feature and list customers subscribed to a feature</Text>
Actually i don't think we need this description

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/tasks/customers_list.task.yaml
> +slug: demo_customers_list
could you also rename the slug to `demo_list_customers` and `list_customers.task.yaml`?

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/tasks/delete_feature_customer.task.yaml
> +slug: demo_delete_feature_customer
rename slug to `demo_disable_feature_for_customer` and file to `disable_feature_for_customer.task.yaml`

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/tasks/create_feature_customer.task.yaml
> +slug: demo_create_feature_customer
rename slug to `demo_enable_feature_for_customer` and file to `enable_feature_for_customer.task.yaml`

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/tasks/list_feature_customers.task.yaml
> +slug: demo_list_feature_customers
rename slug to `demo_list_customers_for_feature` and file to `list_customers_for_feature.task.yaml`

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +          rowSelection="single"
this table doesn't need row selection, can remove this

2022-10-31 19:49 UTC, ericliuche commented on feature_flagging_dashboard/feature_flagging/feature_flagging.view.tsx
> +  { accessor: "updated_at", label: "Last updated", type: "date" },
use `datetime` instead of `date`

2022-11-01 20:13 UTC, ericliuche commented on feature_flagging_dashboard/tasks/list_customers_for_feature.task.yaml
> +name: List customers
Could you fix this name to be `List customers for feature`

2022-11-01 20:13 UTC, ericliuche commented on feature_flagging_dashboard/README.md
> +- Visit the docs to learn more about how to build views: https://docs.airplane.dev/views/getting-started
Could you update the filenames here to reflect the updated filenames?

2022-11-03 21:44 UTC, rose-huang approved these changes

2022-11-03 21:46 UTC, merged