Create team dashboard template
airplanedev/templates pull request #3
Opened 2022-09-09 01:40 UTC by geodn

Working version: https://web.airstage.app/views/vew20220908zgxbjm0khum?__env=prod

We display the employees, unique customers per week, top products, and orders per week. We also allow the the user to select a specific customer and show data specific to them.

2022-09-09 19:07 UTC, rose-huang requested changes
TY so much for working on the template!

2022-09-09 19:07 UTC, rose-huang commented on team_dashboard/team_dashboard/team_dashboard.view.tsx
> +      <Select
Can we add some titles or text in the template to distinguish between the top tables (which seem like an overview of all the external facing stuff) and the bottom that is an overview per customer? I think this would make the template a bit more clear. Or maybe you can have the orders per week and top products show for all of the customers if no customer is selected and then filter on specific customer if you select someone in the dropdown?

2022-09-09 19:07 UTC, rose-huang commented on team_dashboard/team_dashboard/team_dashboard.view.tsx
> +          columns={[{ accessor: "cnt", label: "num_orders" }]}
Let's make the labels more human readable in the title case format of "Column name" ... so something like "Count" or "Number of orders". same for all other columns

2022-09-09 19:07 UTC, rose-huang commented on team_dashboard/README.md
> +- Develop your view locally: `airplane views dev`
Can you mention what demo resources to replace before or after this step?  

I think Zhan has good instructions here https://github.com/airplanedev/templates/blob/main/database_issues_alert/README.md (although should prob add a step for airplane dev in his)

2022-09-12 17:51 UTC, geodn commented on team_dashboard/team_dashboard/team_dashboard.view.tsx
> +        <Table title="Employees" task="list_employees" />
Removed.

2022-09-12 17:51 UTC, geodn commented on team_dashboard/team_dashboard/team_dashboard.view.tsx
> +const TeamDashboard = () => {
Renamed to customer_insights

2022-09-12 18:02 UTC, geodn commented on team_dashboard/README.md
> +- Develop your view locally: `airplane views dev`
Done.

2022-09-12 18:10 UTC, geodn commented
Updated the link to the dashboard, since it got renamed. I added a new table, unique products per week, to fill the hole left by deleting the employees table.

2022-09-13 14:07 UTC, rose-huang requested changes
Thanks for making the changes! Could you update the link with the preview of the template in your description? 

Also sorry for all the nits - be sure to run through the guidance in this doc:  https://www.notion.so/Template-Gallery-how-to-contribute-53af3baef69d40f29a737c0c2522a7c7

2022-09-13 14:07 UTC, rose-huang commented on customer_insights/README.md
> +- If you plan on using this on a different database resource than the demo database, change the demo_db resource in customer_insights.task.yaml to your own database resource's slug
What is `customer_insights.task.yaml`? Can you be more specific with saying to replace the "[Demo DB]"  resource? It also should be replaced with the name of the resource, not slug, I believe.

2022-09-13 14:07 UTC, rose-huang commented on customer_insights/customer_insights/customer_insights.view.tsx
> +            { accessor: "week", type: "date" },
please add a label to this! Also the labels should also be title case ie "Number of orders"

2022-09-13 14:07 UTC, rose-huang commented on customer_insights/README.md
> +- If you plan on using this on a different database resource than the demo database, change the demo_db resource in customer_insights.task.yaml to your own database resource's slug
https://github.com/airplanedev/templates/tree/main/stripe_billing_dashboard is an example of telling users to make changes in multiple files

2022-09-13 14:07 UTC, rose-huang commented on customer_insights/tasks/get_customers_per_week.task.yaml
> +sql:
for all of the task yaml files, can you add a comment above the [Demo DB] resource that's like # Replace [Demo DB] below with your own database resource

2022-09-13 14:10 UTC, rose-huang commented on customer_insights/README.md
> +# Template: Team Dashboard
nit: replace this with new name "Customer insights" in sentence case

2022-09-13 17:04 UTC, geodn commented on customer_insights/customer_insights/customer_insights.view.tsx
> +            { accessor: "week", type: "date" },
Done.

2022-09-13 17:04 UTC, geodn commented on customer_insights/README.md
> +# Template: Team Dashboard
Done.

2022-09-13 17:06 UTC, geodn commented on customer_insights/customer_insights/customer_insights.view.yaml
> +slug: customer_insights
Done.

2022-09-13 17:07 UTC, geodn commented on customer_insights/tasks/get_customers_per_week.task.yaml
> +sql:
Done.

2022-09-13 17:13 UTC, geodn commented on customer_insights/README.md
> +- If you plan on using this on a different database resource than the demo database, change the demo_db resource in customer_insights.task.yaml to your own database resource's slug
Done.

2022-09-13 23:33 UTC, rose-huang approved these changes
Looks awesome, TY so much george 🙏

2022-09-13 23:33 UTC, rose-huang commented on customer_insights/README.md
> +# Template: Customer insights
this looks really great! Sorry one last nit: Can we rename this Template to "Customer insights dashboard" and the outer folder containing everything from `customer_insights` to `customer_insights_dashboard`? I think it will be less confusing if there isn't a nested folder with a view of the same name

2022-09-13 23:33 UTC, rose-huang commented on customer_insights/README.md
> +- Navigate to the customer_insights directory: `cd customer_insights`
can change this to cd `customer_insights_dashboard` as well after updating the folder name

2022-09-14 01:15 UTC, geodn commented on customer_insights/README.md
> +- Navigate to the customer_insights directory: `cd customer_insights`
Done. Also updated package.json

2022-09-14 01:19 UTC, merged