Update templates to use demo_db slug, minor updates to database alert template
airplanedev/templates pull request #30
Opened 2022-11-02 10:29 UTC by zhan-airplane

Minor updates:
* Use demo db slug throughout for consistency
* Switch the order of instructions

Also tested that it works out of the box in editor against stage

2022-11-02 15:55 UTC, rose-huang requested changes
when I run this locally with the studio, it gives me this null error for output and then fails? idk it seems like the await sql built in is not waiting for it to finish like I would expect? 😕 

<img width="1258" alt="Screen Shot 2022-11-02 at 11 54 30 AM" src="https://user-images.githubusercontent.com/34196250/199538054-ba027a40-c5d0-4545-8b40-6f3823186d67.png">

2022-11-02 15:55 UTC, rose-huang commented on database_issues_alert/README.md
>  ## Next steps
nit: can we rename to from `# Template: Database issues alert"

2022-11-02 15:55 UTC, rose-huang commented on database_issues_alert/database_issues_alert.task.yaml
> +  db: "[Demo DB]"
oh actually I think you need this to be the slug or you get this error with airplane dev 😅 

I think the name works for others because they are SQL tasks and not using this resources key but setting resource under the sql key...


```
Discovering tasks, workflows, and views... 

Error: Error reading database_issues_alert.task.yaml

(root): Must validate one and only one schema (oneOf)
resources: Must validate one and only one schema (oneOf)
resources.db: Does not match pattern '^[a-z0-9_]{1,50}$'
(root): Must validate all the schemas (allOf)

For more information on the task definition format, see the docs:
https://docs.airplane.dev/tasks/task-definition
```

2022-11-02 16:28 UTC, zhan-airplane commented
Oh wait @rose-huang you're right I totally was in the wrong directory when I tested it T_T Hmm is this something we should change...? Like between name and slug? It feels kind of inconsistent haha

2022-11-02 16:34 UTC, rose-huang commented
> Hmm is this something we should change...? Like between name and slug? It feels kind of inconsistent haha

I am pro changing the other names to slugs in the SQL yaml definitions and in the READMEs. do you mind doing that in this PR? I think it's actually supposed to be slug according to our docs but I guess name is supported 😅 

https://docs.airplane.dev/tasks/task-definition#sqlresource

2022-11-04 14:58 UTC, rose-huang approved these changes

2022-11-04 15:35 UTC, merged