Improve python selenium template
airplanedev/templates pull request #34
Opened 2022-11-28 14:52 UTC by ericliuche

Updates selenium template to take in a URL parameter and return all links on page

Deployed to stage: https://web.airstage.app/runs/run20221128ze51gfu6ke1?__env=prod

2022-11-29 17:04 UTC, rose-huang requested changes
Oh the template clone command does not install python dependencies IIRC so could you put some instructions in the README for what you need to do in order to get this to work locally?

I pip installed the dependencies and tried running with airplane dev but hit this error

```
Run failed with error
Message: 'geckodriver' executable needs to be in PATH. 

Run created by 
Airplane studio
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/rosehuang/airplanedev/templates/python_selenium_example/.airplane/demo_python_selenium_example/shim.py", line 57, in run
    ret = mod.main(arg_dict)
  File "selenium_example.py", line 11, in main
    with webdriver.Firefox(options=opts) as driver:
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
airplane_output_set:error "Message: 'geckodriver' executable needs to be in PATH. \n"
Run failed - (╯°□°)╯︵ ┻━
```

2022-11-29 17:04 UTC, rose-huang commented on python_selenium_example/selenium_example.py
> +def main(params: Dict[str, Any]) -> List[str]:
why is the return type a list of strings?

2023-01-03 22:59 UTC, ericliuche commented on python_selenium_example/selenium_example.py
> +def main(params: Dict[str, Any]) -> List[str]:
fixed the type

2023-01-04 20:22 UTC, rose-huang approved these changes

2023-01-04 20:23 UTC, merged