Add user impersonation template
airplanedev/templates pull request #5
Opened 2022-09-12 20:28 UTC by stepzhou

2022-09-13 15:59 UTC, rose-huang reviewed
Looking really great so far! Can you also add a `README.md file`? https://github.com/airplanedev/templates/pull/6 has an example of more detailed instructions when you have to replace stuff 

things to mention in README:
- replacing demo db resource
- replace workos api key

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/.gitignore
> +.airplane-view
Zhan added gitignore creation when templates are cloned in CLI so we can remove this! that gitignore currently has `.airplane_view` and `node_modules`

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/package.json
> +    "@workos-inc/node": "^2.12.0",
may be better if we pin workos version in case they release breaking changes?

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/search_users.task.yaml
> +  resource: "DB"
Can we swap out this task to use the Demo DB resource so it works for users when they clone and edit the description of this task?  I think you can use the users table joined with the accounts table

It's also nice to have a version that we can use so feel free to keep the current one and commit it to wherever we are putting airplane views (is it airport?).

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/search_users.task.yaml
> +slug: search_users
prepend all slugs with `demo_` here and in other yaml files

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/impersonate.task.yaml
> +# Used by Airplane to identify your task. Do not change.
nit: let's remove all comments in task yaml's but keep the one at the top - `# Full reference: https://docs.airplane.dev/tasks/task-definition`

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +        showFilter={false}
Let's add columns with labels so that the column namess are in Sentence case

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +                  reasonState.setValue("");
can we reset the other text input and row selection on success? or offer another button to reset?

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/impersonate.js
> +import WorkOS from "@workos-inc/node";
make this a TS task instead of JS

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +import {
nit: it could be slightly confusing in instructions when we tell users to `cd user_impersonation` which directory we are talking about if both the template directory and the view directory are the same name so can we rename one of them? maybe the top level directory to `user_impersonation_dashboard` so we don't have to rename the view files?

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/impersonate.js
> +  const w = new WorkOS(process.env.WORKOS_API_KEY);
let's return a "fake link" if the user doesn't have a `WORKOS_API_KEY` so that this works with dev right when they clone it. 

TAL at an example here: https://github.com/airplanedev/templates/pull/6
in `create_linear_issue.ts` I return fake data and don't actually call the client if the API key isn't there. I also uncomment out the env var in `create_linear_issue.task.yaml` and have instructions in `README.md` for how to use it with your own tokens/api keys

2022-09-13 15:59 UTC, rose-huang commented on user_impersonation/tasks/search_users.sql
> +    users.created_at
might be nice to have their team name  as well

2022-09-13 16:00 UTC, rose-huang requested changes
Forgot to hit RC

2022-09-14 16:48 UTC, rose-huang commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +        showFilter={false}
Also talked to Lee and he mentioned he's trying to migrate people to defining cols outside as a constant so just a heads up - https://github.com/airplanedev/templates/blob/main/stripe_billing_dashboard/stripe_dashboard/stripe_dashboard.view.tsx example

2022-09-15 00:06 UTC, rose-huang commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +import {
Ok another thought - we can name the outer folder to `user_impersonation_tool` instead of dashboard because we use Dashboard too much in names and we can call the name in the package.json the same and use `# Template: User impersonation tool` in the README

2022-09-16 20:04 UTC, stepzhou commented on user_impersonation/user_impersonation/user_impersonation.view.tsx
> +                  reasonState.setValue("");
Changed this to be a modal instead

2022-09-16 20:12 UTC, stepzhou commented
@rose-huang Main change is that I updated this template to use a dialog instead

2022-09-26 20:04 UTC, rose-huang requested changes
A bunch of nits but looks really good!!!

2022-09-26 20:04 UTC, rose-huang commented on user_impersonation_tool/user_impersonation/user_impersonation.view.tsx
> +                setUser(row);
<img width="810" alt="Screen Shot 2022-09-26 at 4 01 39 PM" src="https://user-images.githubusercontent.com/34196250/192368975-9e7781a4-78a0-4c14-b989-13028faccc9e.png">

I get this type error on this line after I pull the branch and yarn install dependencies in the user impersonation tool folder, can you TAL? 🤔

2022-09-27 20:37 UTC, stepzhou commented on user_impersonation_tool/user_impersonation/user_impersonation.view.tsx
> +                setUser(row);
This was due to a breaking change with `rowActions`. Fixed

2022-09-27 20:38 UTC, stepzhou commented on user_impersonation_tool/user_impersonation/user_impersonation.view.tsx
> +### ${user.name}
Made the heading smaller. Not going to muck around with the text size for now. I think what we really need is a description list component

2022-09-28 21:47 UTC, rose-huang approved these changes
Left one comment and bump on the comment
> comment this out envVars section out? README instructions say to "uncomment" this

otw looks good! if you merge this in to main, it should kick off a deployment. could you make sure the views / tasks are in the Templates folder in the prod airplane account? thanks :)

2022-09-28 21:47 UTC, rose-huang commented on user_impersonation_tool/user_impersonation/user_impersonation.view.tsx
> +            <Button
nit: I noticed we recently changed the styling of row actions and saw Lee changed the styling of custom row actions to use buttons with `variant="subtle" compact` - could you try this? idk if it would look weird with the icon so feel free to keep it the same if you think it's better

2022-09-29 19:04 UTC, stepzhou commented on user_impersonation_tool/user_impersonation/user_impersonation.view.tsx
> +            <Button
Looks kinda ugly so I'm gonna keep it as it is!

<img width="241" alt="image" src="https://user-images.githubusercontent.com/1384161/193120214-29a9d64b-9a0e-4821-ba38-fc4f20b91ada.png">

2022-09-29 19:05 UTC, merged

2022-09-29 19:07 UTC, rose-huang commented on user_impersonation_tool/tasks/impersonate.task.yaml
> +  # Get your Linear API key here after logging in: https://workos.com/docs/reference/api-keys
@stepzhou WorkOS API key instead of linear? 😅