Implement Github pr dashboard
airplanedev/templates pull request #8
Opened 2022-09-14 20:03 UTC by leeweisberger

![image](https://user-images.githubusercontent.com/6363419/190251312-fb2f567c-ba9f-4652-bec1-5a270bb94b63.png)

2022-09-14 23:52 UTC, rose-huang requested changes
This looks really great, thanks Lee!! A few comments just for consistency with other templates

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
we'll create a git ignore on clone so we can delete this. also we can add `*/.gitignore` to the this repo's `.gitignore` file if that's helpful lol

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/tasks/tsconfig.json
> +{
can we remove this? without this, the task ts file should just use the tsconfig from the github_pr_dashboard folder right?

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.yaml
> +slug: github_pr_dashboard
nit: prepend "demo_" to slug

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/tasks/list_github_prs.task.yaml
> +name: List PRs
Nit: `List GitHub pull requests` or `List Github PRs` might be more informative? 

if you choose the first one, also rename the files to match `list_github_pull_requests.task.yaml` and `list_github_pull_requests.ts` and update the entrypoint here

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/package.json
> +    "octokit": "^2.0.7",
Probably fine because GitHub shouldn't be that unstable but I've been pinning external packages that aren't initially in package.json in case of any breaking changes

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/tasks/list_github_prs.ts
> +  const authored = createdPullRequestsResponse.data.items
nit: why not rename to `created` here and in the filter? or rename `createdPullRequests` and `createdPullRequestsResponse` to authored if you don't want to update the view

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/README.md
> +# Template: GitHub PR dashboard
README should be in the non-nested `github_pr_dashboard` folder instead of `github_pr_dashboard/github_pr_dashboard`. 

Also it's a bit confusing to have 2 folders of the same name with one nested inside the other. Can you rename the one containing the view to `github_dashboard` or something like that and update the view file names / entrypoint in YAML?

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.tsx
> +                <Title>Open PRs</Title>
I think making the Titles for Open PRs, Approved PRs, and To Review to be smaller size using `order=..`would make them look better

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.tsx
> +          onClick={() => mutate()}
does this not work as well with the task backed button? or did you want loading state and error? curious why you used useTaskMutation

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.tsx
> +          <Text sx={{ maxWidth: 600 }}>{`${pr.body.substring(0, 200)}${
I found this weird bug with the card component as I was testing your view, not blocking but could be nice to update the views version if we fix this in time - https://linear.app/airplane/issue/VIEW-348/text-overflow-with-card-component-does-not-wrap-and-doesnt-scroll

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.yaml
> +name: GitHub PR dashboard
maybe also rename to Github dashboard if we end up renaming files to `github_dashboard`

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/README.md
> +  - Create a config variable in Airplane for `GITHUB_API_KEY`: https://docs.airplane.dev/platform/configs
just curious - if you replace with your github api can you also query non-public PRs?

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.tsx
> +// Put the main logic of the view here.
nit: delete this comment, you can keep the one below

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/tasks/list_github_prs.task.yaml
> +# Used by Airplane to identify your task. Do not change.
nit: delete

2022-09-14 23:52 UTC, rose-huang commented on github_pr_dashboard/tasks/list_github_prs.ts
> +// Put the main logic of the task in this function.
nit: delete

2022-09-15 00:09 UTC, rose-huang commented on github_pr_dashboard/github_pr_dashboard/github_pr_dashboard.view.tsx
> +  useTaskQuery,
don't think you're using this? remove

2022-09-15 14:54 UTC, leeweisberger commented on github_pr_dashboard/tasks/tsconfig.json
> +{
I'll remove. I just ran airplane init and it generated this. we should probably fix this (detect if there is a tsconfig.json in a paretn) like we do for the package.json

2022-09-15 15:00 UTC, leeweisberger commented on github_pr_dashboard/github_pr_dashboard/README.md
> +# Template: GitHub PR dashboard
I get that, but the view isn't a github dashboard. it's a github pull request dashboard...

2022-09-15 15:06 UTC, leeweisberger commented on github_pr_dashboard/tasks/list_github_prs.task.yaml
> +# Used by Airplane to identify your task. Do not change.
We've got this in every task.yaml. Let's delete all of them if we want to

2022-09-15 19:03 UTC, rose-huang commented on github_pr_dashboard/tasks/tsconfig.json
> +{
made a task previously but not sure if it should be triaged to views or tasks or which sprint https://linear.app/airplane/issue/VIEW-120/look-up-for-tsconfig-instead-of-generating-one-in-cwd

2022-09-15 19:11 UTC, rose-huang commented on github_pr_dashboard/tasks/list_github_prs.task.yaml
> +# Used by Airplane to identify your task. Do not change.
oh I meant to delete the comment on line 3 (also now you can kind of change slugs...?). I think the "Full reference" on line 1 can stay.

2022-09-15 19:19 UTC, rose-huang approved these changes
Few nits but looks awesome - thanks Lee!

2022-09-15 19:19 UTC, rose-huang commented on github_pull_request_dashboard/github_pull_request_dashboard/github_pull_request_dashboard.view.tsx
> +      <Title>GitHub Pull Request Dashboard</Title>
nit: sentence case 
```suggestion
      <Title>GitHub pull request dashboard</Title>
```

2022-09-15 19:19 UTC, rose-huang commented on github_pull_request_dashboard/github_pull_request_dashboard/github_pull_request_dashboard.view.tsx
> +                <Title order={3}>✏️ To Review</Title>
nit: sentence case
```suggestion
                <Title order={3}>✏️ PRs to review</Title>
```

2022-09-15 19:19 UTC, rose-huang commented on github_pull_request_dashboard/README.md
> +- Navigate to the github_pr_dashboard directory: `cd github_pr_dashboard`
could you change the top level directory back to `github_pr_dashboard`? makes sense that it's a github pr dashboard not github dashboard but for consistency -

- `name_of_folder` should correspond to `Name of template` in README and in template gallery and README should say to `cd name_of_folder`
- `name_of_folder` should be same as name in `package.json` 
- `name_of_folder_with_view` corresponds to `Name of view` in yaml file and template detail page. should have `name_of_folder_with_view/name_of_folder_with_view.view.tsx` 
- ideally name_of_folder and name_of_folder_with_view are different because the path `github_pull_request_dashboard/github_pull_request_dashboard/github_pull_request_dashboard.view.tsx` feels like too much lol

2022-09-16 04:09 UTC, merged