Add AWS s3 file explorer template
airplanedev/templates pull request #84
Opened 2023-05-01 21:58 UTC by kellymtrinh

You can view this live on staging by searching for "AWS S3 File explorer"

(Please only interact with `test-airplane-bucket` which was set up for OIDC testing).

2023-05-01 22:32 UTC, leeweisberger requested changes

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +          slug: "list_s3_buckets",
I get an error here on render because the selectedRegion.value is not specified on first render. We need to handle the region being undefined

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +    <Stack spacing="lg">
We probably don't need the lg spacing?

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +  const bucketsTableState = useComponentState();
I think we should start adding some generics. We can discuss in the views channel if you want... this would look like `const bucketsTableState = useComponentState<TableStage>();`. It just adds some nice type checking, e.g. telling us that selectedRegion can be undefined

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +      <Label weight="bold">Select a region </Label>{" "}
Remove this label. Use the `label` prop on the select

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +        data={["us-east-1", "us-west-2"]}
Pull these out into a constant at the top outside of the component

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +        defaultValue={"us-east-1"}
Use the constant here

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +          slug: "list_s3_buckets",
Or maybe better is to code this as the default. Something like
```
const region = selectedRegion.value || DEFAULT_REGION
```

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +const ListItems = ({ region, bucketName }) => {
Type these props

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +      <Button
Let's use a secondary button here. Not the primary. Choose a different preset

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +      <Button
This button looks pretty weird all large... maybe change the alignment of the stack and move it to the left or right and see how that looks?

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +    </Stack>
I think we should make this a row action instead. So each row has this button. Easier than selecting a row and then clicking this button

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +      <ListItems
Maybe we should add a divider between here? To separate the buckets from the files? See how that looks

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +const ListItems = ({ region, bucketName }) => {
Can you name this something more descriptive? BucketFiles?

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/tasks/s3_file_explorer.airplane.ts
> +      console.error(err);
We probably want to rethrow this error so that we actually get an error if this fails? As written the task will succeed even if the call fails

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/tasks/s3_file_explorer.airplane.ts
> +    }));
```suggestion
    return (res.Contents ?? []).map((item) => ({
      name: item.Key,
      last_modified: item.LastModified,
      size: item.Size,
    }));
```

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/tasks/s3_file_explorer.airplane.ts
> +    if (!params.item_name) {
Can you just add this to the param validation? The param should be required and non-empty

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/tasks/s3_file_explorer.airplane.ts
> +    const itemBody = (await item.Body?.transformToByteArray()) ?? "";
throw an error here rather than returning an empty string and then uploading the empty string?

2023-05-01 22:32 UTC, leeweisberger commented on aws_s3_file_explorer/README.md
> +- And create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role (ie. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc_test")
hmm what does airplane_oidc_test represent?

2023-05-01 22:51 UTC, kellymtrinh commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +    </Stack>
I just made this a row action and it looks better, but it doesn't actually download since I don't think you can download from the view. We had to make use of the peek. I'll see if I can combine those!

2023-05-01 22:55 UTC, kellymtrinh commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +    </Stack>
Oh nvm you CAN do that!

2023-05-01 23:04 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +    </Stack>
Yeah you can do a row action that opens up the peek! The row action can just be a component that does anything

2023-05-01 23:45 UTC, kellymtrinh commented on aws_s3_file_explorer/README.md
> +- And create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role (ie. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc_test")
Updated this to remove the word test- let me know if that's still not clear. It's the aws role you create when setting up OIDC

2023-05-03 16:55 UTC, leeweisberger approved these changes
Just don't want to reach in for that type in dist views. Feel free to message me if yo uneed help with that

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +        rowSelection="single"
We don't still need row selection right?

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +] satisfies Column[];
Can you throw this at the bottom or top of the file?

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +import { SelectTValue } from "@airplane/views/dist/state/components/select/reducer";
oo I saw someone else do this. Curious where you got this from? We shouldn't be reaching into here

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +  region?: SelectTValue;
Can you use string here? Does it give you issues?

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/README.md
> +- And create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (ie. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`)
i.e. -> e.g.

2023-05-03 16:55 UTC, leeweisberger commented on aws_s3_file_explorer/tasks/s3_file_explorer.airplane.ts
> +    const bucketsInRegion = [];
Type this

conts bucketsInRegion: {name: string, creation_date: string}[] = [];

2023-05-03 16:56 UTC, kellymtrinh commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +import { SelectTValue } from "@airplane/views/dist/state/components/select/reducer";
Oh my typescript linter suggested this as the return value 😱 ...

2023-05-03 16:57 UTC, kellymtrinh commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +  region?: SelectTValue;
Yeah, vscode highlighting says it's SelectTValue

2023-05-03 17:25 UTC, kellymtrinh commented on aws_s3_file_explorer/AWSS3FileExplorer.airplane.tsx
> +  region?: SelectTValue;
Hm writing `string | number` makes the lint error go away. I think it's confusing because VSCode suggests using SelectTValue first.

2023-05-04 21:55 UTC, merged