Add ECS Dashboard template
airplanedev/templates pull request #93
Opened 2023-05-25 05:45 UTC by kkoppenhaver

As part of the Engineering workflows launch, we want to create an ECS Dashboard template

Template Spec: https://www.notion.so/airplanedev/ECS-Dashboard-86fb80f4c48d40c98f309735f3508193

2023-05-25 14:45 UTC, leeweisberger requested changes

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +      <Stack spacing={0}>
Remove this stack?

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +  const clustersState = useComponentState("clusters");
Although I don't think we need to complicate things with generics, I think we should include generics for the state as it just makes programming views a lot easier. So change to `useComponentState<TableState>`. Same for the other useComponentState cases

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +import {
snake_case this file name to be consistent with our other views

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +        <Stack>
Do you need this stack? Can you just remove and replace with `<>` so this stuff is contained in the parent stack?

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +        <Stack>
Same here. Remove if possible

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +        <Stack>
rm

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +                showNotification({ message: "Task stop initiated." }),
make this a success notification (it's an option in the object).

Remove the period.

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +              onSuccess: (o) =>
You can remove the `o` here since you aren't using it

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/package.json
> +    "typescript": "^5.0.4"
Copy what we do for the other templates in terms of pinning versions. e.g. it looks like we usually pin airplane and airplane/views (remove the `^`).

tbh not sure this is the best idea, but let's be consistent and then we can consider changing it

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/cluster_details_airplane.py
> +    return credentials["Credentials"]
add a newline to the bottom of the file. You can configure your editor to do this

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/list_clusters_airplane.py
> +        data.append({'Cluster Name': cluster_arn.split('/').pop(),'Cluster ARN': cluster_arn})
Spaces in object keys are pretty weird. Let's stick with either camelCase or snake_case.

clusterName and clusterARN

Then update the view to use these with `.` notation insted of bracket notation

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/list_clusters_airplane.py
> +    for cluster_arn in response['clusterArns']:
```python
return [{'clusterName': cluster_arn.split('/').pop(), 'clusterArn': cluster_arn} for cluster_arn in response['clusterArns']]
```

Something like that is more pythonic I believe?

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/list_clusters_airplane.py
> +    return credentials["Credentials"]
Can you define this function once and reuse it

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/list_services_airplane.py
> +    return data
Same here. No spaces in key names (camelCase) and maybe use the list comprehension to make it terser

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/list_tasks_airplane.py
> +    return data
Same here

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/stop_task_airplane.py
> +    response = ecs_client.stop_task(cluster=cluster_name, task=task_id)
You're not doing anything with response. Do you want to return something? Or else no need to store the var.

What happens if stopping the task fails? Does it throw an error? Or does response have an error?

2023-05-25 14:45 UTC, leeweisberger commented on ecs_dashboard/tasks/task_details_airplane.py
> +    task_info = response['tasks'][0]['containers'][0]
What if there are no tasks or no containers? This is going to error right?

2023-05-25 14:47 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +          <Heading level={2}>Cluster Details</Heading>
We might want a divider between sections? it looks a little weird how close they are? What do you think?

2023-05-25 14:47 UTC, leeweisberger commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +        <Stack>
Removing this also gives us more space which i think we need

2023-05-26 02:28 UTC, kkoppenhaver commented on ecs_dashboard/tasks/task_details_airplane.py
> +    task_info = response['tasks'][0]['containers'][0]
Because this is the task_details task, it's only triggered when you've selected a Task from the <Table> component and all active tasks will have a container, so I think we should be ok here.

2023-05-26 03:09 UTC, kkoppenhaver commented on ecs_dashboard/tasks/stop_task_airplane.py
> +    response = ecs_client.stop_task(cluster=cluster_name, task=task_id)
Because all this is doing is triggering the stop signal to be sent to the container, I'm not sure we will ever get a response that the stop has failed.

ChatGPT says it will raise a `botocore.exceptions.ClientError`, but looking at the docs, I don't think that's the case, unless it can't reach AWS or something. From the docs:

> When StopTask is called on a task, the equivalent of docker stop is issued to the containers running in the task. This results in a SIGTERM value and a default 30-second timeout, after which the SIGKILL value is sent and the containers are forcibly stopped. If the container handles the SIGTERM value gracefully and exits within 30 seconds from receiving it, no SIGKILL value is sent.

2023-05-26 03:14 UTC, kkoppenhaver commented on ecs_dashboard/EcsDashboard.airplane.tsx
> +          <Heading level={2}>Cluster Details</Heading>
Good call. Added dividers that are visible only when the next section is visible.

2023-05-26 16:34 UTC, kellymtrinh commented on ecs_dashboard/tasks/cluster_details_airplane.py
> +    name="Cluster Details",
NIT: Sentence case so it should be `Cluster details`, `List clusters` etc. for all of the task names

2023-05-31 15:28 UTC, leeweisberger approved these changes

2023-05-31 15:28 UTC, leeweisberger commented on ecs_dashboard/tasks/stop_task_airplane.py
> +    response = ecs_client.stop_task(cluster=cluster_name, task=task_id)
Ok then just remove `response =` since you aren't using the variable. We should really have some python linting htat catches this

2023-05-31 15:28 UTC, leeweisberger commented on ecs_dashboard/ecs_dashboard.airplane.tsx
> +              params: { cluster_name: selectedCluster["Cluster Name"] },
Don't you have to update all these keys now that you chagned them in the tasks?

2023-05-31 15:42 UTC, joshma commented on ecs_dashboard/README.md
> +- And create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (e.g. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`). Make sure that t
```suggestion
- Create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (e.g. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`). Make sure that this role has ECS access so that your Airplane Tasks are able to take ECS actions.
```

2023-05-31 15:42 UTC, joshma commented on ecs_dashboard/README.md
> +- And create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (e.g. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`). Make sure that t
> Make sure that this role has ECS access so that your Airplane Tasks are able to take ECS actions.

I think this needs more detail. Something like "Make sure this role has ECS IAM permissions so that your tasks are able to access the ECS API. You can start by attaching the [AmazonECS_FullAccess policy](https://docs.aws.amazon.com/AmazonECS/latest/userguide/security-iam-awsmanpol.html) to your role."

2023-05-31 22:25 UTC, joshma commented
BTW @kkoppenhaver you should use the "Re-request review" button when it's ready for me to take another look. Assuming there's still some changes pending though (I don't see any mention of that ECS Policy for example)

2023-06-01 06:42 UTC, kkoppenhaver commented on ecs_dashboard/tasks/cluster_details_airplane.py
> +        {'term': 'Name', 'description': cluster_info['clusterName']},
👍 Updated the other tasks that were a similar format as well.

2023-06-01 15:37 UTC, joshma commented on ecs_dashboard/ecs_client/__init__.py
> +    )
missing trailing newline https://github.com/microsoft/vscode/issues/12076#issuecomment-272915821

2023-06-01 15:37 UTC, joshma commented on ecs_dashboard/ecs_client/__init__.py
> +def client(roleArn):
```suggestion
def client(role_arn):
```

2023-06-01 15:38 UTC, joshma commented on ecs_dashboard/ecs_dashboard.airplane.tsx
> +const EcsDashboard = () => {
```suggestion
const ECSDashboard = () => {
```

(style nit, abbrevations should be uppercased)

2023-06-01 15:39 UTC, joshma commented on ecs_dashboard/tasks/list_services_airplane.py
> +    data = []
delete unused variable - ditto for other tasks

2023-06-01 15:39 UTC, joshma commented on ecs_dashboard/tasks/stop_task_airplane.py
> +    ecs.stop_task(cluster=cluster_name, task=task_id)
(fix newline missing)

2023-06-01 15:43 UTC, joshma commented on ecs_dashboard/README.md
> +- Create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (e.g. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`). Make sure this role
Hm I still think this needs to be expanded on a bit, upon re-reading this - as a user, it's probably confusing what all this is.

```
- You'll need to configure [OIDC integration with AWS](...) to authenticate to the AWS APIs. OIDC makes it easy for a task to access the AWS APIs without e.g. hardcoding an AWS API key.
- Using the OIDC integration, this template assumes an AWS role to access the ECS APIs. You'll need to create a role, if you haven't yet, and store that in the `aws_oidc_role` [config variable]. Make sure...
```

2023-06-01 16:03 UTC, kkoppenhaver commented on ecs_dashboard/ecs_dashboard.airplane.tsx
> +const EcsDashboard = () => {
Noted, thanks!

2023-06-01 16:17 UTC, kkoppenhaver commented on ecs_dashboard/README.md
> +- Create a [config variable](https://docs.airplane.dev/platform/configs) named `aws_oidc_role` with the AWS role you created (e.g. `arn:aws:iam::ACCOUNT_ID:role/airplane_oidc"`). Make sure this role
Good call, added a bit to this as well.

2023-06-01 17:18 UTC, joshma approved these changes

2023-06-01 18:36 UTC, merged